// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/account"
	"github.com/Wei-Shaw/sub2api/ent/accountegressbinding"
	"github.com/Wei-Shaw/sub2api/ent/egressroute"
)

// AccountEgressBinding is the model entity for the AccountEgressBinding schema.
type AccountEgressBinding struct {
	config `json:"-"`
	// AccountID holds the value of the "account_id" field.
	AccountID int64 `json:"account_id,omitempty"`
	// RouteID holds the value of the "route_id" field.
	RouteID int64 `json:"route_id,omitempty"`
	// Position holds the value of the "position" field.
	Position int `json:"position,omitempty"`
	// IsPrimary holds the value of the "is_primary" field.
	IsPrimary bool `json:"is_primary,omitempty"`
	// Status holds the value of the "status" field.
	Status accountegressbinding.Status `json:"status,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the AccountEgressBindingQuery when eager-loading is set.
	Edges        AccountEgressBindingEdges `json:"edges"`
	selectValues sql.SelectValues
}

// AccountEgressBindingEdges holds the relations/edges for other nodes in the graph.
type AccountEgressBindingEdges struct {
	// Account holds the value of the account edge.
	Account *Account `json:"account,omitempty"`
	// Route holds the value of the route edge.
	Route *EgressRoute `json:"route,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// AccountOrErr returns the Account value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AccountEgressBindingEdges) AccountOrErr() (*Account, error) {
	if e.Account != nil {
		return e.Account, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: account.Label}
	}
	return nil, &NotLoadedError{edge: "account"}
}

// RouteOrErr returns the Route value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AccountEgressBindingEdges) RouteOrErr() (*EgressRoute, error) {
	if e.Route != nil {
		return e.Route, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: egressroute.Label}
	}
	return nil, &NotLoadedError{edge: "route"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AccountEgressBinding) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case accountegressbinding.FieldIsPrimary:
			values[i] = new(sql.NullBool)
		case accountegressbinding.FieldAccountID, accountegressbinding.FieldRouteID, accountegressbinding.FieldPosition:
			values[i] = new(sql.NullInt64)
		case accountegressbinding.FieldStatus:
			values[i] = new(sql.NullString)
		case accountegressbinding.FieldCreatedAt, accountegressbinding.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AccountEgressBinding fields.
func (_m *AccountEgressBinding) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case accountegressbinding.FieldAccountID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field account_id", values[i])
			} else if value.Valid {
				_m.AccountID = value.Int64
			}
		case accountegressbinding.FieldRouteID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field route_id", values[i])
			} else if value.Valid {
				_m.RouteID = value.Int64
			}
		case accountegressbinding.FieldPosition:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field position", values[i])
			} else if value.Valid {
				_m.Position = int(value.Int64)
			}
		case accountegressbinding.FieldIsPrimary:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_primary", values[i])
			} else if value.Valid {
				_m.IsPrimary = value.Bool
			}
		case accountegressbinding.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = accountegressbinding.Status(value.String)
			}
		case accountegressbinding.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case accountegressbinding.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AccountEgressBinding.
// This includes values selected through modifiers, order, etc.
func (_m *AccountEgressBinding) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryAccount queries the "account" edge of the AccountEgressBinding entity.
func (_m *AccountEgressBinding) QueryAccount() *AccountQuery {
	return NewAccountEgressBindingClient(_m.config).QueryAccount(_m)
}

// QueryRoute queries the "route" edge of the AccountEgressBinding entity.
func (_m *AccountEgressBinding) QueryRoute() *EgressRouteQuery {
	return NewAccountEgressBindingClient(_m.config).QueryRoute(_m)
}

// Update returns a builder for updating this AccountEgressBinding.
// Note that you need to call AccountEgressBinding.Unwrap() before calling this method if this AccountEgressBinding
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *AccountEgressBinding) Update() *AccountEgressBindingUpdateOne {
	return NewAccountEgressBindingClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the AccountEgressBinding entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *AccountEgressBinding) Unwrap() *AccountEgressBinding {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: AccountEgressBinding is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *AccountEgressBinding) String() string {
	var builder strings.Builder
	builder.WriteString("AccountEgressBinding(")
	builder.WriteString("account_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.AccountID))
	builder.WriteString(", ")
	builder.WriteString("route_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.RouteID))
	builder.WriteString(", ")
	builder.WriteString("position=")
	builder.WriteString(fmt.Sprintf("%v", _m.Position))
	builder.WriteString(", ")
	builder.WriteString("is_primary=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsPrimary))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// AccountEgressBindings is a parsable slice of AccountEgressBinding.
type AccountEgressBindings []*AccountEgressBinding
