// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/account"
	"github.com/Wei-Shaw/sub2api/ent/accountegressbinding"
	"github.com/Wei-Shaw/sub2api/ent/egressroute"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// AccountEgressBindingQuery is the builder for querying AccountEgressBinding entities.
type AccountEgressBindingQuery struct {
	config
	ctx         *QueryContext
	order       []accountegressbinding.OrderOption
	inters      []Interceptor
	predicates  []predicate.AccountEgressBinding
	withAccount *AccountQuery
	withRoute   *EgressRouteQuery
	modifiers   []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the AccountEgressBindingQuery builder.
func (_q *AccountEgressBindingQuery) Where(ps ...predicate.AccountEgressBinding) *AccountEgressBindingQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *AccountEgressBindingQuery) Limit(limit int) *AccountEgressBindingQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *AccountEgressBindingQuery) Offset(offset int) *AccountEgressBindingQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *AccountEgressBindingQuery) Unique(unique bool) *AccountEgressBindingQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *AccountEgressBindingQuery) Order(o ...accountegressbinding.OrderOption) *AccountEgressBindingQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryAccount chains the current query on the "account" edge.
func (_q *AccountEgressBindingQuery) QueryAccount() *AccountQuery {
	query := (&AccountClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(accountegressbinding.Table, accountegressbinding.AccountColumn, selector),
			sqlgraph.To(account.Table, account.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, accountegressbinding.AccountTable, accountegressbinding.AccountColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryRoute chains the current query on the "route" edge.
func (_q *AccountEgressBindingQuery) QueryRoute() *EgressRouteQuery {
	query := (&EgressRouteClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(accountegressbinding.Table, accountegressbinding.RouteColumn, selector),
			sqlgraph.To(egressroute.Table, egressroute.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, accountegressbinding.RouteTable, accountegressbinding.RouteColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first AccountEgressBinding entity from the query.
// Returns a *NotFoundError when no AccountEgressBinding was found.
func (_q *AccountEgressBindingQuery) First(ctx context.Context) (*AccountEgressBinding, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{accountegressbinding.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *AccountEgressBindingQuery) FirstX(ctx context.Context) *AccountEgressBinding {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// Only returns a single AccountEgressBinding entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one AccountEgressBinding entity is found.
// Returns a *NotFoundError when no AccountEgressBinding entities are found.
func (_q *AccountEgressBindingQuery) Only(ctx context.Context) (*AccountEgressBinding, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{accountegressbinding.Label}
	default:
		return nil, &NotSingularError{accountegressbinding.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *AccountEgressBindingQuery) OnlyX(ctx context.Context) *AccountEgressBinding {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// All executes the query and returns a list of AccountEgressBindings.
func (_q *AccountEgressBindingQuery) All(ctx context.Context) ([]*AccountEgressBinding, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*AccountEgressBinding, *AccountEgressBindingQuery]()
	return withInterceptors[[]*AccountEgressBinding](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *AccountEgressBindingQuery) AllX(ctx context.Context) []*AccountEgressBinding {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// Count returns the count of the given query.
func (_q *AccountEgressBindingQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*AccountEgressBindingQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *AccountEgressBindingQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *AccountEgressBindingQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.First(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *AccountEgressBindingQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the AccountEgressBindingQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *AccountEgressBindingQuery) Clone() *AccountEgressBindingQuery {
	if _q == nil {
		return nil
	}
	return &AccountEgressBindingQuery{
		config:      _q.config,
		ctx:         _q.ctx.Clone(),
		order:       append([]accountegressbinding.OrderOption{}, _q.order...),
		inters:      append([]Interceptor{}, _q.inters...),
		predicates:  append([]predicate.AccountEgressBinding{}, _q.predicates...),
		withAccount: _q.withAccount.Clone(),
		withRoute:   _q.withRoute.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithAccount tells the query-builder to eager-load the nodes that are connected to
// the "account" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *AccountEgressBindingQuery) WithAccount(opts ...func(*AccountQuery)) *AccountEgressBindingQuery {
	query := (&AccountClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withAccount = query
	return _q
}

// WithRoute tells the query-builder to eager-load the nodes that are connected to
// the "route" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *AccountEgressBindingQuery) WithRoute(opts ...func(*EgressRouteQuery)) *AccountEgressBindingQuery {
	query := (&EgressRouteClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withRoute = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		AccountID int64 `json:"account_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.AccountEgressBinding.Query().
//		GroupBy(accountegressbinding.FieldAccountID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *AccountEgressBindingQuery) GroupBy(field string, fields ...string) *AccountEgressBindingGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &AccountEgressBindingGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = accountegressbinding.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		AccountID int64 `json:"account_id,omitempty"`
//	}
//
//	client.AccountEgressBinding.Query().
//		Select(accountegressbinding.FieldAccountID).
//		Scan(ctx, &v)
func (_q *AccountEgressBindingQuery) Select(fields ...string) *AccountEgressBindingSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &AccountEgressBindingSelect{AccountEgressBindingQuery: _q}
	sbuild.label = accountegressbinding.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a AccountEgressBindingSelect configured with the given aggregations.
func (_q *AccountEgressBindingQuery) Aggregate(fns ...AggregateFunc) *AccountEgressBindingSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *AccountEgressBindingQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !accountegressbinding.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *AccountEgressBindingQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*AccountEgressBinding, error) {
	var (
		nodes       = []*AccountEgressBinding{}
		_spec       = _q.querySpec()
		loadedTypes = [2]bool{
			_q.withAccount != nil,
			_q.withRoute != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*AccountEgressBinding).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &AccountEgressBinding{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withAccount; query != nil {
		if err := _q.loadAccount(ctx, query, nodes, nil,
			func(n *AccountEgressBinding, e *Account) { n.Edges.Account = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withRoute; query != nil {
		if err := _q.loadRoute(ctx, query, nodes, nil,
			func(n *AccountEgressBinding, e *EgressRoute) { n.Edges.Route = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *AccountEgressBindingQuery) loadAccount(ctx context.Context, query *AccountQuery, nodes []*AccountEgressBinding, init func(*AccountEgressBinding), assign func(*AccountEgressBinding, *Account)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*AccountEgressBinding)
	for i := range nodes {
		fk := nodes[i].AccountID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(account.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "account_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *AccountEgressBindingQuery) loadRoute(ctx context.Context, query *EgressRouteQuery, nodes []*AccountEgressBinding, init func(*AccountEgressBinding), assign func(*AccountEgressBinding, *EgressRoute)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*AccountEgressBinding)
	for i := range nodes {
		fk := nodes[i].RouteID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(egressroute.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "route_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *AccountEgressBindingQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Unique = false
	_spec.Node.Columns = nil
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *AccountEgressBindingQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(accountegressbinding.Table, accountegressbinding.Columns, nil)
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		for i := range fields {
			_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
		}
		if _q.withAccount != nil {
			_spec.Node.AddColumnOnce(accountegressbinding.FieldAccountID)
		}
		if _q.withRoute != nil {
			_spec.Node.AddColumnOnce(accountegressbinding.FieldRouteID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *AccountEgressBindingQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(accountegressbinding.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = accountegressbinding.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range _q.modifiers {
		m(selector)
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (_q *AccountEgressBindingQuery) ForUpdate(opts ...sql.LockOption) *AccountEgressBindingQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return _q
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (_q *AccountEgressBindingQuery) ForShare(opts ...sql.LockOption) *AccountEgressBindingQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return _q
}

// AccountEgressBindingGroupBy is the group-by builder for AccountEgressBinding entities.
type AccountEgressBindingGroupBy struct {
	selector
	build *AccountEgressBindingQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *AccountEgressBindingGroupBy) Aggregate(fns ...AggregateFunc) *AccountEgressBindingGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *AccountEgressBindingGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*AccountEgressBindingQuery, *AccountEgressBindingGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *AccountEgressBindingGroupBy) sqlScan(ctx context.Context, root *AccountEgressBindingQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// AccountEgressBindingSelect is the builder for selecting fields of AccountEgressBinding entities.
type AccountEgressBindingSelect struct {
	*AccountEgressBindingQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *AccountEgressBindingSelect) Aggregate(fns ...AggregateFunc) *AccountEgressBindingSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *AccountEgressBindingSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*AccountEgressBindingQuery, *AccountEgressBindingSelect](ctx, _s.AccountEgressBindingQuery, _s, _s.inters, v)
}

func (_s *AccountEgressBindingSelect) sqlScan(ctx context.Context, root *AccountEgressBindingQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
