// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/account"
	"github.com/Wei-Shaw/sub2api/ent/accountegressbinding"
	"github.com/Wei-Shaw/sub2api/ent/egressroute"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// AccountEgressBindingUpdate is the builder for updating AccountEgressBinding entities.
type AccountEgressBindingUpdate struct {
	config
	hooks    []Hook
	mutation *AccountEgressBindingMutation
}

// Where appends a list predicates to the AccountEgressBindingUpdate builder.
func (_u *AccountEgressBindingUpdate) Where(ps ...predicate.AccountEgressBinding) *AccountEgressBindingUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *AccountEgressBindingUpdate) SetAccountID(v int64) *AccountEgressBindingUpdate {
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *AccountEgressBindingUpdate) SetNillableAccountID(v *int64) *AccountEgressBindingUpdate {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// SetRouteID sets the "route_id" field.
func (_u *AccountEgressBindingUpdate) SetRouteID(v int64) *AccountEgressBindingUpdate {
	_u.mutation.SetRouteID(v)
	return _u
}

// SetNillableRouteID sets the "route_id" field if the given value is not nil.
func (_u *AccountEgressBindingUpdate) SetNillableRouteID(v *int64) *AccountEgressBindingUpdate {
	if v != nil {
		_u.SetRouteID(*v)
	}
	return _u
}

// SetPosition sets the "position" field.
func (_u *AccountEgressBindingUpdate) SetPosition(v int) *AccountEgressBindingUpdate {
	_u.mutation.ResetPosition()
	_u.mutation.SetPosition(v)
	return _u
}

// SetNillablePosition sets the "position" field if the given value is not nil.
func (_u *AccountEgressBindingUpdate) SetNillablePosition(v *int) *AccountEgressBindingUpdate {
	if v != nil {
		_u.SetPosition(*v)
	}
	return _u
}

// AddPosition adds value to the "position" field.
func (_u *AccountEgressBindingUpdate) AddPosition(v int) *AccountEgressBindingUpdate {
	_u.mutation.AddPosition(v)
	return _u
}

// SetIsPrimary sets the "is_primary" field.
func (_u *AccountEgressBindingUpdate) SetIsPrimary(v bool) *AccountEgressBindingUpdate {
	_u.mutation.SetIsPrimary(v)
	return _u
}

// SetNillableIsPrimary sets the "is_primary" field if the given value is not nil.
func (_u *AccountEgressBindingUpdate) SetNillableIsPrimary(v *bool) *AccountEgressBindingUpdate {
	if v != nil {
		_u.SetIsPrimary(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *AccountEgressBindingUpdate) SetStatus(v accountegressbinding.Status) *AccountEgressBindingUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *AccountEgressBindingUpdate) SetNillableStatus(v *accountegressbinding.Status) *AccountEgressBindingUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AccountEgressBindingUpdate) SetUpdatedAt(v time.Time) *AccountEgressBindingUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetAccount sets the "account" edge to the Account entity.
func (_u *AccountEgressBindingUpdate) SetAccount(v *Account) *AccountEgressBindingUpdate {
	return _u.SetAccountID(v.ID)
}

// SetRoute sets the "route" edge to the EgressRoute entity.
func (_u *AccountEgressBindingUpdate) SetRoute(v *EgressRoute) *AccountEgressBindingUpdate {
	return _u.SetRouteID(v.ID)
}

// Mutation returns the AccountEgressBindingMutation object of the builder.
func (_u *AccountEgressBindingUpdate) Mutation() *AccountEgressBindingMutation {
	return _u.mutation
}

// ClearAccount clears the "account" edge to the Account entity.
func (_u *AccountEgressBindingUpdate) ClearAccount() *AccountEgressBindingUpdate {
	_u.mutation.ClearAccount()
	return _u
}

// ClearRoute clears the "route" edge to the EgressRoute entity.
func (_u *AccountEgressBindingUpdate) ClearRoute() *AccountEgressBindingUpdate {
	_u.mutation.ClearRoute()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AccountEgressBindingUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AccountEgressBindingUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AccountEgressBindingUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AccountEgressBindingUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AccountEgressBindingUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := accountegressbinding.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AccountEgressBindingUpdate) check() error {
	if v, ok := _u.mutation.Position(); ok {
		if err := accountegressbinding.PositionValidator(v); err != nil {
			return &ValidationError{Name: "position", err: fmt.Errorf(`ent: validator failed for field "AccountEgressBinding.position": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := accountegressbinding.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "AccountEgressBinding.status": %w`, err)}
		}
	}
	if _u.mutation.AccountCleared() && len(_u.mutation.AccountIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AccountEgressBinding.account"`)
	}
	if _u.mutation.RouteCleared() && len(_u.mutation.RouteIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AccountEgressBinding.route"`)
	}
	return nil
}

func (_u *AccountEgressBindingUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(accountegressbinding.Table, accountegressbinding.Columns, sqlgraph.NewFieldSpec(accountegressbinding.FieldAccountID, field.TypeInt64), sqlgraph.NewFieldSpec(accountegressbinding.FieldRouteID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Position(); ok {
		_spec.SetField(accountegressbinding.FieldPosition, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPosition(); ok {
		_spec.AddField(accountegressbinding.FieldPosition, field.TypeInt, value)
	}
	if value, ok := _u.mutation.IsPrimary(); ok {
		_spec.SetField(accountegressbinding.FieldIsPrimary, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(accountegressbinding.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(accountegressbinding.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.AccountCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   accountegressbinding.AccountTable,
			Columns: []string{accountegressbinding.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   accountegressbinding.AccountTable,
			Columns: []string{accountegressbinding.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RouteCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   accountegressbinding.RouteTable,
			Columns: []string{accountegressbinding.RouteColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(egressroute.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RouteIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   accountegressbinding.RouteTable,
			Columns: []string{accountegressbinding.RouteColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(egressroute.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{accountegressbinding.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AccountEgressBindingUpdateOne is the builder for updating a single AccountEgressBinding entity.
type AccountEgressBindingUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AccountEgressBindingMutation
}

// SetAccountID sets the "account_id" field.
func (_u *AccountEgressBindingUpdateOne) SetAccountID(v int64) *AccountEgressBindingUpdateOne {
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *AccountEgressBindingUpdateOne) SetNillableAccountID(v *int64) *AccountEgressBindingUpdateOne {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// SetRouteID sets the "route_id" field.
func (_u *AccountEgressBindingUpdateOne) SetRouteID(v int64) *AccountEgressBindingUpdateOne {
	_u.mutation.SetRouteID(v)
	return _u
}

// SetNillableRouteID sets the "route_id" field if the given value is not nil.
func (_u *AccountEgressBindingUpdateOne) SetNillableRouteID(v *int64) *AccountEgressBindingUpdateOne {
	if v != nil {
		_u.SetRouteID(*v)
	}
	return _u
}

// SetPosition sets the "position" field.
func (_u *AccountEgressBindingUpdateOne) SetPosition(v int) *AccountEgressBindingUpdateOne {
	_u.mutation.ResetPosition()
	_u.mutation.SetPosition(v)
	return _u
}

// SetNillablePosition sets the "position" field if the given value is not nil.
func (_u *AccountEgressBindingUpdateOne) SetNillablePosition(v *int) *AccountEgressBindingUpdateOne {
	if v != nil {
		_u.SetPosition(*v)
	}
	return _u
}

// AddPosition adds value to the "position" field.
func (_u *AccountEgressBindingUpdateOne) AddPosition(v int) *AccountEgressBindingUpdateOne {
	_u.mutation.AddPosition(v)
	return _u
}

// SetIsPrimary sets the "is_primary" field.
func (_u *AccountEgressBindingUpdateOne) SetIsPrimary(v bool) *AccountEgressBindingUpdateOne {
	_u.mutation.SetIsPrimary(v)
	return _u
}

// SetNillableIsPrimary sets the "is_primary" field if the given value is not nil.
func (_u *AccountEgressBindingUpdateOne) SetNillableIsPrimary(v *bool) *AccountEgressBindingUpdateOne {
	if v != nil {
		_u.SetIsPrimary(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *AccountEgressBindingUpdateOne) SetStatus(v accountegressbinding.Status) *AccountEgressBindingUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *AccountEgressBindingUpdateOne) SetNillableStatus(v *accountegressbinding.Status) *AccountEgressBindingUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AccountEgressBindingUpdateOne) SetUpdatedAt(v time.Time) *AccountEgressBindingUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetAccount sets the "account" edge to the Account entity.
func (_u *AccountEgressBindingUpdateOne) SetAccount(v *Account) *AccountEgressBindingUpdateOne {
	return _u.SetAccountID(v.ID)
}

// SetRoute sets the "route" edge to the EgressRoute entity.
func (_u *AccountEgressBindingUpdateOne) SetRoute(v *EgressRoute) *AccountEgressBindingUpdateOne {
	return _u.SetRouteID(v.ID)
}

// Mutation returns the AccountEgressBindingMutation object of the builder.
func (_u *AccountEgressBindingUpdateOne) Mutation() *AccountEgressBindingMutation {
	return _u.mutation
}

// ClearAccount clears the "account" edge to the Account entity.
func (_u *AccountEgressBindingUpdateOne) ClearAccount() *AccountEgressBindingUpdateOne {
	_u.mutation.ClearAccount()
	return _u
}

// ClearRoute clears the "route" edge to the EgressRoute entity.
func (_u *AccountEgressBindingUpdateOne) ClearRoute() *AccountEgressBindingUpdateOne {
	_u.mutation.ClearRoute()
	return _u
}

// Where appends a list predicates to the AccountEgressBindingUpdate builder.
func (_u *AccountEgressBindingUpdateOne) Where(ps ...predicate.AccountEgressBinding) *AccountEgressBindingUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AccountEgressBindingUpdateOne) Select(field string, fields ...string) *AccountEgressBindingUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AccountEgressBinding entity.
func (_u *AccountEgressBindingUpdateOne) Save(ctx context.Context) (*AccountEgressBinding, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AccountEgressBindingUpdateOne) SaveX(ctx context.Context) *AccountEgressBinding {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AccountEgressBindingUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AccountEgressBindingUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AccountEgressBindingUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := accountegressbinding.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AccountEgressBindingUpdateOne) check() error {
	if v, ok := _u.mutation.Position(); ok {
		if err := accountegressbinding.PositionValidator(v); err != nil {
			return &ValidationError{Name: "position", err: fmt.Errorf(`ent: validator failed for field "AccountEgressBinding.position": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := accountegressbinding.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "AccountEgressBinding.status": %w`, err)}
		}
	}
	if _u.mutation.AccountCleared() && len(_u.mutation.AccountIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AccountEgressBinding.account"`)
	}
	if _u.mutation.RouteCleared() && len(_u.mutation.RouteIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AccountEgressBinding.route"`)
	}
	return nil
}

func (_u *AccountEgressBindingUpdateOne) sqlSave(ctx context.Context) (_node *AccountEgressBinding, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(accountegressbinding.Table, accountegressbinding.Columns, sqlgraph.NewFieldSpec(accountegressbinding.FieldAccountID, field.TypeInt64), sqlgraph.NewFieldSpec(accountegressbinding.FieldRouteID, field.TypeInt64))
	if id, ok := _u.mutation.AccountID(); !ok {
		return nil, &ValidationError{Name: "account_id", err: errors.New(`ent: missing "AccountEgressBinding.account_id" for update`)}
	} else {
		_spec.Node.CompositeID[0].Value = id
	}
	if id, ok := _u.mutation.RouteID(); !ok {
		return nil, &ValidationError{Name: "route_id", err: errors.New(`ent: missing "AccountEgressBinding.route_id" for update`)}
	} else {
		_spec.Node.CompositeID[1].Value = id
	}
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, len(fields))
		for i, f := range fields {
			if !accountegressbinding.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			_spec.Node.Columns[i] = f
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Position(); ok {
		_spec.SetField(accountegressbinding.FieldPosition, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPosition(); ok {
		_spec.AddField(accountegressbinding.FieldPosition, field.TypeInt, value)
	}
	if value, ok := _u.mutation.IsPrimary(); ok {
		_spec.SetField(accountegressbinding.FieldIsPrimary, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(accountegressbinding.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(accountegressbinding.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.AccountCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   accountegressbinding.AccountTable,
			Columns: []string{accountegressbinding.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   accountegressbinding.AccountTable,
			Columns: []string{accountegressbinding.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RouteCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   accountegressbinding.RouteTable,
			Columns: []string{accountegressbinding.RouteColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(egressroute.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RouteIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   accountegressbinding.RouteTable,
			Columns: []string{accountegressbinding.RouteColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(egressroute.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &AccountEgressBinding{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{accountegressbinding.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
