// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/account"
	"github.com/Wei-Shaw/sub2api/ent/accountegressbinding"
	"github.com/Wei-Shaw/sub2api/ent/egressroute"
)

// AccountEgressBindingCreate is the builder for creating a AccountEgressBinding entity.
type AccountEgressBindingCreate struct {
	config
	mutation *AccountEgressBindingMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetAccountID sets the "account_id" field.
func (_c *AccountEgressBindingCreate) SetAccountID(v int64) *AccountEgressBindingCreate {
	_c.mutation.SetAccountID(v)
	return _c
}

// SetRouteID sets the "route_id" field.
func (_c *AccountEgressBindingCreate) SetRouteID(v int64) *AccountEgressBindingCreate {
	_c.mutation.SetRouteID(v)
	return _c
}

// SetPosition sets the "position" field.
func (_c *AccountEgressBindingCreate) SetPosition(v int) *AccountEgressBindingCreate {
	_c.mutation.SetPosition(v)
	return _c
}

// SetNillablePosition sets the "position" field if the given value is not nil.
func (_c *AccountEgressBindingCreate) SetNillablePosition(v *int) *AccountEgressBindingCreate {
	if v != nil {
		_c.SetPosition(*v)
	}
	return _c
}

// SetIsPrimary sets the "is_primary" field.
func (_c *AccountEgressBindingCreate) SetIsPrimary(v bool) *AccountEgressBindingCreate {
	_c.mutation.SetIsPrimary(v)
	return _c
}

// SetNillableIsPrimary sets the "is_primary" field if the given value is not nil.
func (_c *AccountEgressBindingCreate) SetNillableIsPrimary(v *bool) *AccountEgressBindingCreate {
	if v != nil {
		_c.SetIsPrimary(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *AccountEgressBindingCreate) SetStatus(v accountegressbinding.Status) *AccountEgressBindingCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *AccountEgressBindingCreate) SetNillableStatus(v *accountegressbinding.Status) *AccountEgressBindingCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *AccountEgressBindingCreate) SetCreatedAt(v time.Time) *AccountEgressBindingCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AccountEgressBindingCreate) SetNillableCreatedAt(v *time.Time) *AccountEgressBindingCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *AccountEgressBindingCreate) SetUpdatedAt(v time.Time) *AccountEgressBindingCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *AccountEgressBindingCreate) SetNillableUpdatedAt(v *time.Time) *AccountEgressBindingCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetAccount sets the "account" edge to the Account entity.
func (_c *AccountEgressBindingCreate) SetAccount(v *Account) *AccountEgressBindingCreate {
	return _c.SetAccountID(v.ID)
}

// SetRoute sets the "route" edge to the EgressRoute entity.
func (_c *AccountEgressBindingCreate) SetRoute(v *EgressRoute) *AccountEgressBindingCreate {
	return _c.SetRouteID(v.ID)
}

// Mutation returns the AccountEgressBindingMutation object of the builder.
func (_c *AccountEgressBindingCreate) Mutation() *AccountEgressBindingMutation {
	return _c.mutation
}

// Save creates the AccountEgressBinding in the database.
func (_c *AccountEgressBindingCreate) Save(ctx context.Context) (*AccountEgressBinding, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AccountEgressBindingCreate) SaveX(ctx context.Context) *AccountEgressBinding {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AccountEgressBindingCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AccountEgressBindingCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AccountEgressBindingCreate) defaults() {
	if _, ok := _c.mutation.Position(); !ok {
		v := accountegressbinding.DefaultPosition
		_c.mutation.SetPosition(v)
	}
	if _, ok := _c.mutation.IsPrimary(); !ok {
		v := accountegressbinding.DefaultIsPrimary
		_c.mutation.SetIsPrimary(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := accountegressbinding.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := accountegressbinding.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := accountegressbinding.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AccountEgressBindingCreate) check() error {
	if _, ok := _c.mutation.AccountID(); !ok {
		return &ValidationError{Name: "account_id", err: errors.New(`ent: missing required field "AccountEgressBinding.account_id"`)}
	}
	if _, ok := _c.mutation.RouteID(); !ok {
		return &ValidationError{Name: "route_id", err: errors.New(`ent: missing required field "AccountEgressBinding.route_id"`)}
	}
	if _, ok := _c.mutation.Position(); !ok {
		return &ValidationError{Name: "position", err: errors.New(`ent: missing required field "AccountEgressBinding.position"`)}
	}
	if v, ok := _c.mutation.Position(); ok {
		if err := accountegressbinding.PositionValidator(v); err != nil {
			return &ValidationError{Name: "position", err: fmt.Errorf(`ent: validator failed for field "AccountEgressBinding.position": %w`, err)}
		}
	}
	if _, ok := _c.mutation.IsPrimary(); !ok {
		return &ValidationError{Name: "is_primary", err: errors.New(`ent: missing required field "AccountEgressBinding.is_primary"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "AccountEgressBinding.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := accountegressbinding.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "AccountEgressBinding.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "AccountEgressBinding.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "AccountEgressBinding.updated_at"`)}
	}
	if len(_c.mutation.AccountIDs()) == 0 {
		return &ValidationError{Name: "account", err: errors.New(`ent: missing required edge "AccountEgressBinding.account"`)}
	}
	if len(_c.mutation.RouteIDs()) == 0 {
		return &ValidationError{Name: "route", err: errors.New(`ent: missing required edge "AccountEgressBinding.route"`)}
	}
	return nil
}

func (_c *AccountEgressBindingCreate) sqlSave(ctx context.Context) (*AccountEgressBinding, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	return _node, nil
}

func (_c *AccountEgressBindingCreate) createSpec() (*AccountEgressBinding, *sqlgraph.CreateSpec) {
	var (
		_node = &AccountEgressBinding{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(accountegressbinding.Table, nil)
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Position(); ok {
		_spec.SetField(accountegressbinding.FieldPosition, field.TypeInt, value)
		_node.Position = value
	}
	if value, ok := _c.mutation.IsPrimary(); ok {
		_spec.SetField(accountegressbinding.FieldIsPrimary, field.TypeBool, value)
		_node.IsPrimary = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(accountegressbinding.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(accountegressbinding.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(accountegressbinding.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.AccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   accountegressbinding.AccountTable,
			Columns: []string{accountegressbinding.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.AccountID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.RouteIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   accountegressbinding.RouteTable,
			Columns: []string{accountegressbinding.RouteColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(egressroute.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.RouteID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AccountEgressBinding.Create().
//		SetAccountID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AccountEgressBindingUpsert) {
//			SetAccountID(v+v).
//		}).
//		Exec(ctx)
func (_c *AccountEgressBindingCreate) OnConflict(opts ...sql.ConflictOption) *AccountEgressBindingUpsertOne {
	_c.conflict = opts
	return &AccountEgressBindingUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AccountEgressBinding.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AccountEgressBindingCreate) OnConflictColumns(columns ...string) *AccountEgressBindingUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AccountEgressBindingUpsertOne{
		create: _c,
	}
}

type (
	// AccountEgressBindingUpsertOne is the builder for "upsert"-ing
	//  one AccountEgressBinding node.
	AccountEgressBindingUpsertOne struct {
		create *AccountEgressBindingCreate
	}

	// AccountEgressBindingUpsert is the "OnConflict" setter.
	AccountEgressBindingUpsert struct {
		*sql.UpdateSet
	}
)

// SetAccountID sets the "account_id" field.
func (u *AccountEgressBindingUpsert) SetAccountID(v int64) *AccountEgressBindingUpsert {
	u.Set(accountegressbinding.FieldAccountID, v)
	return u
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *AccountEgressBindingUpsert) UpdateAccountID() *AccountEgressBindingUpsert {
	u.SetExcluded(accountegressbinding.FieldAccountID)
	return u
}

// SetRouteID sets the "route_id" field.
func (u *AccountEgressBindingUpsert) SetRouteID(v int64) *AccountEgressBindingUpsert {
	u.Set(accountegressbinding.FieldRouteID, v)
	return u
}

// UpdateRouteID sets the "route_id" field to the value that was provided on create.
func (u *AccountEgressBindingUpsert) UpdateRouteID() *AccountEgressBindingUpsert {
	u.SetExcluded(accountegressbinding.FieldRouteID)
	return u
}

// SetPosition sets the "position" field.
func (u *AccountEgressBindingUpsert) SetPosition(v int) *AccountEgressBindingUpsert {
	u.Set(accountegressbinding.FieldPosition, v)
	return u
}

// UpdatePosition sets the "position" field to the value that was provided on create.
func (u *AccountEgressBindingUpsert) UpdatePosition() *AccountEgressBindingUpsert {
	u.SetExcluded(accountegressbinding.FieldPosition)
	return u
}

// AddPosition adds v to the "position" field.
func (u *AccountEgressBindingUpsert) AddPosition(v int) *AccountEgressBindingUpsert {
	u.Add(accountegressbinding.FieldPosition, v)
	return u
}

// SetIsPrimary sets the "is_primary" field.
func (u *AccountEgressBindingUpsert) SetIsPrimary(v bool) *AccountEgressBindingUpsert {
	u.Set(accountegressbinding.FieldIsPrimary, v)
	return u
}

// UpdateIsPrimary sets the "is_primary" field to the value that was provided on create.
func (u *AccountEgressBindingUpsert) UpdateIsPrimary() *AccountEgressBindingUpsert {
	u.SetExcluded(accountegressbinding.FieldIsPrimary)
	return u
}

// SetStatus sets the "status" field.
func (u *AccountEgressBindingUpsert) SetStatus(v accountegressbinding.Status) *AccountEgressBindingUpsert {
	u.Set(accountegressbinding.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *AccountEgressBindingUpsert) UpdateStatus() *AccountEgressBindingUpsert {
	u.SetExcluded(accountegressbinding.FieldStatus)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AccountEgressBindingUpsert) SetUpdatedAt(v time.Time) *AccountEgressBindingUpsert {
	u.Set(accountegressbinding.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AccountEgressBindingUpsert) UpdateUpdatedAt() *AccountEgressBindingUpsert {
	u.SetExcluded(accountegressbinding.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.AccountEgressBinding.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *AccountEgressBindingUpsertOne) UpdateNewValues() *AccountEgressBindingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(accountegressbinding.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AccountEgressBinding.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *AccountEgressBindingUpsertOne) Ignore() *AccountEgressBindingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AccountEgressBindingUpsertOne) DoNothing() *AccountEgressBindingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AccountEgressBindingCreate.OnConflict
// documentation for more info.
func (u *AccountEgressBindingUpsertOne) Update(set func(*AccountEgressBindingUpsert)) *AccountEgressBindingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AccountEgressBindingUpsert{UpdateSet: update})
	}))
	return u
}

// SetAccountID sets the "account_id" field.
func (u *AccountEgressBindingUpsertOne) SetAccountID(v int64) *AccountEgressBindingUpsertOne {
	return u.Update(func(s *AccountEgressBindingUpsert) {
		s.SetAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *AccountEgressBindingUpsertOne) UpdateAccountID() *AccountEgressBindingUpsertOne {
	return u.Update(func(s *AccountEgressBindingUpsert) {
		s.UpdateAccountID()
	})
}

// SetRouteID sets the "route_id" field.
func (u *AccountEgressBindingUpsertOne) SetRouteID(v int64) *AccountEgressBindingUpsertOne {
	return u.Update(func(s *AccountEgressBindingUpsert) {
		s.SetRouteID(v)
	})
}

// UpdateRouteID sets the "route_id" field to the value that was provided on create.
func (u *AccountEgressBindingUpsertOne) UpdateRouteID() *AccountEgressBindingUpsertOne {
	return u.Update(func(s *AccountEgressBindingUpsert) {
		s.UpdateRouteID()
	})
}

// SetPosition sets the "position" field.
func (u *AccountEgressBindingUpsertOne) SetPosition(v int) *AccountEgressBindingUpsertOne {
	return u.Update(func(s *AccountEgressBindingUpsert) {
		s.SetPosition(v)
	})
}

// AddPosition adds v to the "position" field.
func (u *AccountEgressBindingUpsertOne) AddPosition(v int) *AccountEgressBindingUpsertOne {
	return u.Update(func(s *AccountEgressBindingUpsert) {
		s.AddPosition(v)
	})
}

// UpdatePosition sets the "position" field to the value that was provided on create.
func (u *AccountEgressBindingUpsertOne) UpdatePosition() *AccountEgressBindingUpsertOne {
	return u.Update(func(s *AccountEgressBindingUpsert) {
		s.UpdatePosition()
	})
}

// SetIsPrimary sets the "is_primary" field.
func (u *AccountEgressBindingUpsertOne) SetIsPrimary(v bool) *AccountEgressBindingUpsertOne {
	return u.Update(func(s *AccountEgressBindingUpsert) {
		s.SetIsPrimary(v)
	})
}

// UpdateIsPrimary sets the "is_primary" field to the value that was provided on create.
func (u *AccountEgressBindingUpsertOne) UpdateIsPrimary() *AccountEgressBindingUpsertOne {
	return u.Update(func(s *AccountEgressBindingUpsert) {
		s.UpdateIsPrimary()
	})
}

// SetStatus sets the "status" field.
func (u *AccountEgressBindingUpsertOne) SetStatus(v accountegressbinding.Status) *AccountEgressBindingUpsertOne {
	return u.Update(func(s *AccountEgressBindingUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *AccountEgressBindingUpsertOne) UpdateStatus() *AccountEgressBindingUpsertOne {
	return u.Update(func(s *AccountEgressBindingUpsert) {
		s.UpdateStatus()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AccountEgressBindingUpsertOne) SetUpdatedAt(v time.Time) *AccountEgressBindingUpsertOne {
	return u.Update(func(s *AccountEgressBindingUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AccountEgressBindingUpsertOne) UpdateUpdatedAt() *AccountEgressBindingUpsertOne {
	return u.Update(func(s *AccountEgressBindingUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *AccountEgressBindingUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AccountEgressBindingCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AccountEgressBindingUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// AccountEgressBindingCreateBulk is the builder for creating many AccountEgressBinding entities in bulk.
type AccountEgressBindingCreateBulk struct {
	config
	err      error
	builders []*AccountEgressBindingCreate
	conflict []sql.ConflictOption
}

// Save creates the AccountEgressBinding entities in the database.
func (_c *AccountEgressBindingCreateBulk) Save(ctx context.Context) ([]*AccountEgressBinding, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AccountEgressBinding, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AccountEgressBindingMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AccountEgressBindingCreateBulk) SaveX(ctx context.Context) []*AccountEgressBinding {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AccountEgressBindingCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AccountEgressBindingCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AccountEgressBinding.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AccountEgressBindingUpsert) {
//			SetAccountID(v+v).
//		}).
//		Exec(ctx)
func (_c *AccountEgressBindingCreateBulk) OnConflict(opts ...sql.ConflictOption) *AccountEgressBindingUpsertBulk {
	_c.conflict = opts
	return &AccountEgressBindingUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AccountEgressBinding.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AccountEgressBindingCreateBulk) OnConflictColumns(columns ...string) *AccountEgressBindingUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AccountEgressBindingUpsertBulk{
		create: _c,
	}
}

// AccountEgressBindingUpsertBulk is the builder for "upsert"-ing
// a bulk of AccountEgressBinding nodes.
type AccountEgressBindingUpsertBulk struct {
	create *AccountEgressBindingCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.AccountEgressBinding.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *AccountEgressBindingUpsertBulk) UpdateNewValues() *AccountEgressBindingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(accountegressbinding.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AccountEgressBinding.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *AccountEgressBindingUpsertBulk) Ignore() *AccountEgressBindingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AccountEgressBindingUpsertBulk) DoNothing() *AccountEgressBindingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AccountEgressBindingCreateBulk.OnConflict
// documentation for more info.
func (u *AccountEgressBindingUpsertBulk) Update(set func(*AccountEgressBindingUpsert)) *AccountEgressBindingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AccountEgressBindingUpsert{UpdateSet: update})
	}))
	return u
}

// SetAccountID sets the "account_id" field.
func (u *AccountEgressBindingUpsertBulk) SetAccountID(v int64) *AccountEgressBindingUpsertBulk {
	return u.Update(func(s *AccountEgressBindingUpsert) {
		s.SetAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *AccountEgressBindingUpsertBulk) UpdateAccountID() *AccountEgressBindingUpsertBulk {
	return u.Update(func(s *AccountEgressBindingUpsert) {
		s.UpdateAccountID()
	})
}

// SetRouteID sets the "route_id" field.
func (u *AccountEgressBindingUpsertBulk) SetRouteID(v int64) *AccountEgressBindingUpsertBulk {
	return u.Update(func(s *AccountEgressBindingUpsert) {
		s.SetRouteID(v)
	})
}

// UpdateRouteID sets the "route_id" field to the value that was provided on create.
func (u *AccountEgressBindingUpsertBulk) UpdateRouteID() *AccountEgressBindingUpsertBulk {
	return u.Update(func(s *AccountEgressBindingUpsert) {
		s.UpdateRouteID()
	})
}

// SetPosition sets the "position" field.
func (u *AccountEgressBindingUpsertBulk) SetPosition(v int) *AccountEgressBindingUpsertBulk {
	return u.Update(func(s *AccountEgressBindingUpsert) {
		s.SetPosition(v)
	})
}

// AddPosition adds v to the "position" field.
func (u *AccountEgressBindingUpsertBulk) AddPosition(v int) *AccountEgressBindingUpsertBulk {
	return u.Update(func(s *AccountEgressBindingUpsert) {
		s.AddPosition(v)
	})
}

// UpdatePosition sets the "position" field to the value that was provided on create.
func (u *AccountEgressBindingUpsertBulk) UpdatePosition() *AccountEgressBindingUpsertBulk {
	return u.Update(func(s *AccountEgressBindingUpsert) {
		s.UpdatePosition()
	})
}

// SetIsPrimary sets the "is_primary" field.
func (u *AccountEgressBindingUpsertBulk) SetIsPrimary(v bool) *AccountEgressBindingUpsertBulk {
	return u.Update(func(s *AccountEgressBindingUpsert) {
		s.SetIsPrimary(v)
	})
}

// UpdateIsPrimary sets the "is_primary" field to the value that was provided on create.
func (u *AccountEgressBindingUpsertBulk) UpdateIsPrimary() *AccountEgressBindingUpsertBulk {
	return u.Update(func(s *AccountEgressBindingUpsert) {
		s.UpdateIsPrimary()
	})
}

// SetStatus sets the "status" field.
func (u *AccountEgressBindingUpsertBulk) SetStatus(v accountegressbinding.Status) *AccountEgressBindingUpsertBulk {
	return u.Update(func(s *AccountEgressBindingUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *AccountEgressBindingUpsertBulk) UpdateStatus() *AccountEgressBindingUpsertBulk {
	return u.Update(func(s *AccountEgressBindingUpsert) {
		s.UpdateStatus()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AccountEgressBindingUpsertBulk) SetUpdatedAt(v time.Time) *AccountEgressBindingUpsertBulk {
	return u.Update(func(s *AccountEgressBindingUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AccountEgressBindingUpsertBulk) UpdateUpdatedAt() *AccountEgressBindingUpsertBulk {
	return u.Update(func(s *AccountEgressBindingUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *AccountEgressBindingUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the AccountEgressBindingCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AccountEgressBindingCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AccountEgressBindingUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
