// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/egressidentity"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// EgressIdentityDelete is the builder for deleting a EgressIdentity entity.
type EgressIdentityDelete struct {
	config
	hooks    []Hook
	mutation *EgressIdentityMutation
}

// Where appends a list predicates to the EgressIdentityDelete builder.
func (_d *EgressIdentityDelete) Where(ps ...predicate.EgressIdentity) *EgressIdentityDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *EgressIdentityDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *EgressIdentityDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *EgressIdentityDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(egressidentity.Table, sqlgraph.NewFieldSpec(egressidentity.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// EgressIdentityDeleteOne is the builder for deleting a single EgressIdentity entity.
type EgressIdentityDeleteOne struct {
	_d *EgressIdentityDelete
}

// Where appends a list predicates to the EgressIdentityDelete builder.
func (_d *EgressIdentityDeleteOne) Where(ps ...predicate.EgressIdentity) *EgressIdentityDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *EgressIdentityDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{egressidentity.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *EgressIdentityDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
