// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/egressidentity"
	"github.com/Wei-Shaw/sub2api/ent/egressroute"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// EgressIdentityUpdate is the builder for updating EgressIdentity entities.
type EgressIdentityUpdate struct {
	config
	hooks    []Hook
	mutation *EgressIdentityMutation
}

// Where appends a list predicates to the EgressIdentityUpdate builder.
func (_u *EgressIdentityUpdate) Where(ps ...predicate.EgressIdentity) *EgressIdentityUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *EgressIdentityUpdate) SetUpdatedAt(v time.Time) *EgressIdentityUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetPublicIP sets the "public_ip" field.
func (_u *EgressIdentityUpdate) SetPublicIP(v string) *EgressIdentityUpdate {
	_u.mutation.SetPublicIP(v)
	return _u
}

// SetNillablePublicIP sets the "public_ip" field if the given value is not nil.
func (_u *EgressIdentityUpdate) SetNillablePublicIP(v *string) *EgressIdentityUpdate {
	if v != nil {
		_u.SetPublicIP(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *EgressIdentityUpdate) SetStatus(v egressidentity.Status) *EgressIdentityUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *EgressIdentityUpdate) SetNillableStatus(v *egressidentity.Status) *EgressIdentityUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// AddRouteIDs adds the "routes" edge to the EgressRoute entity by IDs.
func (_u *EgressIdentityUpdate) AddRouteIDs(ids ...int64) *EgressIdentityUpdate {
	_u.mutation.AddRouteIDs(ids...)
	return _u
}

// AddRoutes adds the "routes" edges to the EgressRoute entity.
func (_u *EgressIdentityUpdate) AddRoutes(v ...*EgressRoute) *EgressIdentityUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRouteIDs(ids...)
}

// Mutation returns the EgressIdentityMutation object of the builder.
func (_u *EgressIdentityUpdate) Mutation() *EgressIdentityMutation {
	return _u.mutation
}

// ClearRoutes clears all "routes" edges to the EgressRoute entity.
func (_u *EgressIdentityUpdate) ClearRoutes() *EgressIdentityUpdate {
	_u.mutation.ClearRoutes()
	return _u
}

// RemoveRouteIDs removes the "routes" edge to EgressRoute entities by IDs.
func (_u *EgressIdentityUpdate) RemoveRouteIDs(ids ...int64) *EgressIdentityUpdate {
	_u.mutation.RemoveRouteIDs(ids...)
	return _u
}

// RemoveRoutes removes "routes" edges to EgressRoute entities.
func (_u *EgressIdentityUpdate) RemoveRoutes(v ...*EgressRoute) *EgressIdentityUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRouteIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *EgressIdentityUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EgressIdentityUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *EgressIdentityUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EgressIdentityUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *EgressIdentityUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := egressidentity.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *EgressIdentityUpdate) check() error {
	if v, ok := _u.mutation.PublicIP(); ok {
		if err := egressidentity.PublicIPValidator(v); err != nil {
			return &ValidationError{Name: "public_ip", err: fmt.Errorf(`ent: validator failed for field "EgressIdentity.public_ip": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := egressidentity.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "EgressIdentity.status": %w`, err)}
		}
	}
	return nil
}

func (_u *EgressIdentityUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(egressidentity.Table, egressidentity.Columns, sqlgraph.NewFieldSpec(egressidentity.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(egressidentity.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.PublicIP(); ok {
		_spec.SetField(egressidentity.FieldPublicIP, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(egressidentity.FieldStatus, field.TypeEnum, value)
	}
	if _u.mutation.RoutesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   egressidentity.RoutesTable,
			Columns: []string{egressidentity.RoutesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(egressroute.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRoutesIDs(); len(nodes) > 0 && !_u.mutation.RoutesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   egressidentity.RoutesTable,
			Columns: []string{egressidentity.RoutesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(egressroute.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RoutesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   egressidentity.RoutesTable,
			Columns: []string{egressidentity.RoutesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(egressroute.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{egressidentity.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// EgressIdentityUpdateOne is the builder for updating a single EgressIdentity entity.
type EgressIdentityUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *EgressIdentityMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *EgressIdentityUpdateOne) SetUpdatedAt(v time.Time) *EgressIdentityUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetPublicIP sets the "public_ip" field.
func (_u *EgressIdentityUpdateOne) SetPublicIP(v string) *EgressIdentityUpdateOne {
	_u.mutation.SetPublicIP(v)
	return _u
}

// SetNillablePublicIP sets the "public_ip" field if the given value is not nil.
func (_u *EgressIdentityUpdateOne) SetNillablePublicIP(v *string) *EgressIdentityUpdateOne {
	if v != nil {
		_u.SetPublicIP(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *EgressIdentityUpdateOne) SetStatus(v egressidentity.Status) *EgressIdentityUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *EgressIdentityUpdateOne) SetNillableStatus(v *egressidentity.Status) *EgressIdentityUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// AddRouteIDs adds the "routes" edge to the EgressRoute entity by IDs.
func (_u *EgressIdentityUpdateOne) AddRouteIDs(ids ...int64) *EgressIdentityUpdateOne {
	_u.mutation.AddRouteIDs(ids...)
	return _u
}

// AddRoutes adds the "routes" edges to the EgressRoute entity.
func (_u *EgressIdentityUpdateOne) AddRoutes(v ...*EgressRoute) *EgressIdentityUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRouteIDs(ids...)
}

// Mutation returns the EgressIdentityMutation object of the builder.
func (_u *EgressIdentityUpdateOne) Mutation() *EgressIdentityMutation {
	return _u.mutation
}

// ClearRoutes clears all "routes" edges to the EgressRoute entity.
func (_u *EgressIdentityUpdateOne) ClearRoutes() *EgressIdentityUpdateOne {
	_u.mutation.ClearRoutes()
	return _u
}

// RemoveRouteIDs removes the "routes" edge to EgressRoute entities by IDs.
func (_u *EgressIdentityUpdateOne) RemoveRouteIDs(ids ...int64) *EgressIdentityUpdateOne {
	_u.mutation.RemoveRouteIDs(ids...)
	return _u
}

// RemoveRoutes removes "routes" edges to EgressRoute entities.
func (_u *EgressIdentityUpdateOne) RemoveRoutes(v ...*EgressRoute) *EgressIdentityUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRouteIDs(ids...)
}

// Where appends a list predicates to the EgressIdentityUpdate builder.
func (_u *EgressIdentityUpdateOne) Where(ps ...predicate.EgressIdentity) *EgressIdentityUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *EgressIdentityUpdateOne) Select(field string, fields ...string) *EgressIdentityUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated EgressIdentity entity.
func (_u *EgressIdentityUpdateOne) Save(ctx context.Context) (*EgressIdentity, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EgressIdentityUpdateOne) SaveX(ctx context.Context) *EgressIdentity {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *EgressIdentityUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EgressIdentityUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *EgressIdentityUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := egressidentity.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *EgressIdentityUpdateOne) check() error {
	if v, ok := _u.mutation.PublicIP(); ok {
		if err := egressidentity.PublicIPValidator(v); err != nil {
			return &ValidationError{Name: "public_ip", err: fmt.Errorf(`ent: validator failed for field "EgressIdentity.public_ip": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := egressidentity.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "EgressIdentity.status": %w`, err)}
		}
	}
	return nil
}

func (_u *EgressIdentityUpdateOne) sqlSave(ctx context.Context) (_node *EgressIdentity, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(egressidentity.Table, egressidentity.Columns, sqlgraph.NewFieldSpec(egressidentity.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "EgressIdentity.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, egressidentity.FieldID)
		for _, f := range fields {
			if !egressidentity.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != egressidentity.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(egressidentity.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.PublicIP(); ok {
		_spec.SetField(egressidentity.FieldPublicIP, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(egressidentity.FieldStatus, field.TypeEnum, value)
	}
	if _u.mutation.RoutesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   egressidentity.RoutesTable,
			Columns: []string{egressidentity.RoutesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(egressroute.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRoutesIDs(); len(nodes) > 0 && !_u.mutation.RoutesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   egressidentity.RoutesTable,
			Columns: []string{egressidentity.RoutesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(egressroute.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RoutesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   egressidentity.RoutesTable,
			Columns: []string{egressidentity.RoutesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(egressroute.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &EgressIdentity{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{egressidentity.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
