// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/account"
	"github.com/Wei-Shaw/sub2api/ent/egressidentity"
	"github.com/Wei-Shaw/sub2api/ent/egressroute"
	"github.com/Wei-Shaw/sub2api/ent/proxy"
)

// EgressRouteCreate is the builder for creating a EgressRoute entity.
type EgressRouteCreate struct {
	config
	mutation *EgressRouteMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *EgressRouteCreate) SetCreatedAt(v time.Time) *EgressRouteCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *EgressRouteCreate) SetNillableCreatedAt(v *time.Time) *EgressRouteCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *EgressRouteCreate) SetUpdatedAt(v time.Time) *EgressRouteCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *EgressRouteCreate) SetNillableUpdatedAt(v *time.Time) *EgressRouteCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetKind sets the "kind" field.
func (_c *EgressRouteCreate) SetKind(v egressroute.Kind) *EgressRouteCreate {
	_c.mutation.SetKind(v)
	return _c
}

// SetProxyID sets the "proxy_id" field.
func (_c *EgressRouteCreate) SetProxyID(v int64) *EgressRouteCreate {
	_c.mutation.SetProxyID(v)
	return _c
}

// SetNillableProxyID sets the "proxy_id" field if the given value is not nil.
func (_c *EgressRouteCreate) SetNillableProxyID(v *int64) *EgressRouteCreate {
	if v != nil {
		_c.SetProxyID(*v)
	}
	return _c
}

// SetRuntimeScope sets the "runtime_scope" field.
func (_c *EgressRouteCreate) SetRuntimeScope(v string) *EgressRouteCreate {
	_c.mutation.SetRuntimeScope(v)
	return _c
}

// SetNillableRuntimeScope sets the "runtime_scope" field if the given value is not nil.
func (_c *EgressRouteCreate) SetNillableRuntimeScope(v *string) *EgressRouteCreate {
	if v != nil {
		_c.SetRuntimeScope(*v)
	}
	return _c
}

// SetExpectedIdentityID sets the "expected_identity_id" field.
func (_c *EgressRouteCreate) SetExpectedIdentityID(v int64) *EgressRouteCreate {
	_c.mutation.SetExpectedIdentityID(v)
	return _c
}

// SetNillableExpectedIdentityID sets the "expected_identity_id" field if the given value is not nil.
func (_c *EgressRouteCreate) SetNillableExpectedIdentityID(v *int64) *EgressRouteCreate {
	if v != nil {
		_c.SetExpectedIdentityID(*v)
	}
	return _c
}

// SetState sets the "state" field.
func (_c *EgressRouteCreate) SetState(v egressroute.State) *EgressRouteCreate {
	_c.mutation.SetState(v)
	return _c
}

// SetNillableState sets the "state" field if the given value is not nil.
func (_c *EgressRouteCreate) SetNillableState(v *egressroute.State) *EgressRouteCreate {
	if v != nil {
		_c.SetState(*v)
	}
	return _c
}

// SetLastObservedIP sets the "last_observed_ip" field.
func (_c *EgressRouteCreate) SetLastObservedIP(v string) *EgressRouteCreate {
	_c.mutation.SetLastObservedIP(v)
	return _c
}

// SetNillableLastObservedIP sets the "last_observed_ip" field if the given value is not nil.
func (_c *EgressRouteCreate) SetNillableLastObservedIP(v *string) *EgressRouteCreate {
	if v != nil {
		_c.SetLastObservedIP(*v)
	}
	return _c
}

// SetLastProbedAt sets the "last_probed_at" field.
func (_c *EgressRouteCreate) SetLastProbedAt(v time.Time) *EgressRouteCreate {
	_c.mutation.SetLastProbedAt(v)
	return _c
}

// SetNillableLastProbedAt sets the "last_probed_at" field if the given value is not nil.
func (_c *EgressRouteCreate) SetNillableLastProbedAt(v *time.Time) *EgressRouteCreate {
	if v != nil {
		_c.SetLastProbedAt(*v)
	}
	return _c
}

// SetVerifiedAt sets the "verified_at" field.
func (_c *EgressRouteCreate) SetVerifiedAt(v time.Time) *EgressRouteCreate {
	_c.mutation.SetVerifiedAt(v)
	return _c
}

// SetNillableVerifiedAt sets the "verified_at" field if the given value is not nil.
func (_c *EgressRouteCreate) SetNillableVerifiedAt(v *time.Time) *EgressRouteCreate {
	if v != nil {
		_c.SetVerifiedAt(*v)
	}
	return _c
}

// SetRevision sets the "revision" field.
func (_c *EgressRouteCreate) SetRevision(v int64) *EgressRouteCreate {
	_c.mutation.SetRevision(v)
	return _c
}

// SetNillableRevision sets the "revision" field if the given value is not nil.
func (_c *EgressRouteCreate) SetNillableRevision(v *int64) *EgressRouteCreate {
	if v != nil {
		_c.SetRevision(*v)
	}
	return _c
}

// SetLastError sets the "last_error" field.
func (_c *EgressRouteCreate) SetLastError(v string) *EgressRouteCreate {
	_c.mutation.SetLastError(v)
	return _c
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_c *EgressRouteCreate) SetNillableLastError(v *string) *EgressRouteCreate {
	if v != nil {
		_c.SetLastError(*v)
	}
	return _c
}

// SetProxy sets the "proxy" edge to the Proxy entity.
func (_c *EgressRouteCreate) SetProxy(v *Proxy) *EgressRouteCreate {
	return _c.SetProxyID(v.ID)
}

// SetExpectedIdentity sets the "expected_identity" edge to the EgressIdentity entity.
func (_c *EgressRouteCreate) SetExpectedIdentity(v *EgressIdentity) *EgressRouteCreate {
	return _c.SetExpectedIdentityID(v.ID)
}

// AddAccountIDs adds the "accounts" edge to the Account entity by IDs.
func (_c *EgressRouteCreate) AddAccountIDs(ids ...int64) *EgressRouteCreate {
	_c.mutation.AddAccountIDs(ids...)
	return _c
}

// AddAccounts adds the "accounts" edges to the Account entity.
func (_c *EgressRouteCreate) AddAccounts(v ...*Account) *EgressRouteCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddAccountIDs(ids...)
}

// Mutation returns the EgressRouteMutation object of the builder.
func (_c *EgressRouteCreate) Mutation() *EgressRouteMutation {
	return _c.mutation
}

// Save creates the EgressRoute in the database.
func (_c *EgressRouteCreate) Save(ctx context.Context) (*EgressRoute, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *EgressRouteCreate) SaveX(ctx context.Context) *EgressRoute {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EgressRouteCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EgressRouteCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *EgressRouteCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := egressroute.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := egressroute.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.State(); !ok {
		v := egressroute.DefaultState
		_c.mutation.SetState(v)
	}
	if _, ok := _c.mutation.Revision(); !ok {
		v := egressroute.DefaultRevision
		_c.mutation.SetRevision(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *EgressRouteCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "EgressRoute.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "EgressRoute.updated_at"`)}
	}
	if _, ok := _c.mutation.Kind(); !ok {
		return &ValidationError{Name: "kind", err: errors.New(`ent: missing required field "EgressRoute.kind"`)}
	}
	if v, ok := _c.mutation.Kind(); ok {
		if err := egressroute.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "EgressRoute.kind": %w`, err)}
		}
	}
	if v, ok := _c.mutation.RuntimeScope(); ok {
		if err := egressroute.RuntimeScopeValidator(v); err != nil {
			return &ValidationError{Name: "runtime_scope", err: fmt.Errorf(`ent: validator failed for field "EgressRoute.runtime_scope": %w`, err)}
		}
	}
	if _, ok := _c.mutation.State(); !ok {
		return &ValidationError{Name: "state", err: errors.New(`ent: missing required field "EgressRoute.state"`)}
	}
	if v, ok := _c.mutation.State(); ok {
		if err := egressroute.StateValidator(v); err != nil {
			return &ValidationError{Name: "state", err: fmt.Errorf(`ent: validator failed for field "EgressRoute.state": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Revision(); !ok {
		return &ValidationError{Name: "revision", err: errors.New(`ent: missing required field "EgressRoute.revision"`)}
	}
	if v, ok := _c.mutation.Revision(); ok {
		if err := egressroute.RevisionValidator(v); err != nil {
			return &ValidationError{Name: "revision", err: fmt.Errorf(`ent: validator failed for field "EgressRoute.revision": %w`, err)}
		}
	}
	return nil
}

func (_c *EgressRouteCreate) sqlSave(ctx context.Context) (*EgressRoute, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *EgressRouteCreate) createSpec() (*EgressRoute, *sqlgraph.CreateSpec) {
	var (
		_node = &EgressRoute{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(egressroute.Table, sqlgraph.NewFieldSpec(egressroute.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(egressroute.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(egressroute.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Kind(); ok {
		_spec.SetField(egressroute.FieldKind, field.TypeEnum, value)
		_node.Kind = value
	}
	if value, ok := _c.mutation.RuntimeScope(); ok {
		_spec.SetField(egressroute.FieldRuntimeScope, field.TypeString, value)
		_node.RuntimeScope = &value
	}
	if value, ok := _c.mutation.State(); ok {
		_spec.SetField(egressroute.FieldState, field.TypeEnum, value)
		_node.State = value
	}
	if value, ok := _c.mutation.LastObservedIP(); ok {
		_spec.SetField(egressroute.FieldLastObservedIP, field.TypeString, value)
		_node.LastObservedIP = &value
	}
	if value, ok := _c.mutation.LastProbedAt(); ok {
		_spec.SetField(egressroute.FieldLastProbedAt, field.TypeTime, value)
		_node.LastProbedAt = &value
	}
	if value, ok := _c.mutation.VerifiedAt(); ok {
		_spec.SetField(egressroute.FieldVerifiedAt, field.TypeTime, value)
		_node.VerifiedAt = &value
	}
	if value, ok := _c.mutation.Revision(); ok {
		_spec.SetField(egressroute.FieldRevision, field.TypeInt64, value)
		_node.Revision = value
	}
	if value, ok := _c.mutation.LastError(); ok {
		_spec.SetField(egressroute.FieldLastError, field.TypeString, value)
		_node.LastError = &value
	}
	if nodes := _c.mutation.ProxyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   egressroute.ProxyTable,
			Columns: []string{egressroute.ProxyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(proxy.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ProxyID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ExpectedIdentityIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   egressroute.ExpectedIdentityTable,
			Columns: []string{egressroute.ExpectedIdentityColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(egressidentity.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ExpectedIdentityID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.AccountsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   egressroute.AccountsTable,
			Columns: egressroute.AccountsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &AccountEgressBindingCreate{config: _c.config, mutation: newAccountEgressBindingMutation(_c.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.EgressRoute.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.EgressRouteUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *EgressRouteCreate) OnConflict(opts ...sql.ConflictOption) *EgressRouteUpsertOne {
	_c.conflict = opts
	return &EgressRouteUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.EgressRoute.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *EgressRouteCreate) OnConflictColumns(columns ...string) *EgressRouteUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &EgressRouteUpsertOne{
		create: _c,
	}
}

type (
	// EgressRouteUpsertOne is the builder for "upsert"-ing
	//  one EgressRoute node.
	EgressRouteUpsertOne struct {
		create *EgressRouteCreate
	}

	// EgressRouteUpsert is the "OnConflict" setter.
	EgressRouteUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *EgressRouteUpsert) SetUpdatedAt(v time.Time) *EgressRouteUpsert {
	u.Set(egressroute.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *EgressRouteUpsert) UpdateUpdatedAt() *EgressRouteUpsert {
	u.SetExcluded(egressroute.FieldUpdatedAt)
	return u
}

// SetKind sets the "kind" field.
func (u *EgressRouteUpsert) SetKind(v egressroute.Kind) *EgressRouteUpsert {
	u.Set(egressroute.FieldKind, v)
	return u
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *EgressRouteUpsert) UpdateKind() *EgressRouteUpsert {
	u.SetExcluded(egressroute.FieldKind)
	return u
}

// SetProxyID sets the "proxy_id" field.
func (u *EgressRouteUpsert) SetProxyID(v int64) *EgressRouteUpsert {
	u.Set(egressroute.FieldProxyID, v)
	return u
}

// UpdateProxyID sets the "proxy_id" field to the value that was provided on create.
func (u *EgressRouteUpsert) UpdateProxyID() *EgressRouteUpsert {
	u.SetExcluded(egressroute.FieldProxyID)
	return u
}

// ClearProxyID clears the value of the "proxy_id" field.
func (u *EgressRouteUpsert) ClearProxyID() *EgressRouteUpsert {
	u.SetNull(egressroute.FieldProxyID)
	return u
}

// SetRuntimeScope sets the "runtime_scope" field.
func (u *EgressRouteUpsert) SetRuntimeScope(v string) *EgressRouteUpsert {
	u.Set(egressroute.FieldRuntimeScope, v)
	return u
}

// UpdateRuntimeScope sets the "runtime_scope" field to the value that was provided on create.
func (u *EgressRouteUpsert) UpdateRuntimeScope() *EgressRouteUpsert {
	u.SetExcluded(egressroute.FieldRuntimeScope)
	return u
}

// ClearRuntimeScope clears the value of the "runtime_scope" field.
func (u *EgressRouteUpsert) ClearRuntimeScope() *EgressRouteUpsert {
	u.SetNull(egressroute.FieldRuntimeScope)
	return u
}

// SetExpectedIdentityID sets the "expected_identity_id" field.
func (u *EgressRouteUpsert) SetExpectedIdentityID(v int64) *EgressRouteUpsert {
	u.Set(egressroute.FieldExpectedIdentityID, v)
	return u
}

// UpdateExpectedIdentityID sets the "expected_identity_id" field to the value that was provided on create.
func (u *EgressRouteUpsert) UpdateExpectedIdentityID() *EgressRouteUpsert {
	u.SetExcluded(egressroute.FieldExpectedIdentityID)
	return u
}

// ClearExpectedIdentityID clears the value of the "expected_identity_id" field.
func (u *EgressRouteUpsert) ClearExpectedIdentityID() *EgressRouteUpsert {
	u.SetNull(egressroute.FieldExpectedIdentityID)
	return u
}

// SetState sets the "state" field.
func (u *EgressRouteUpsert) SetState(v egressroute.State) *EgressRouteUpsert {
	u.Set(egressroute.FieldState, v)
	return u
}

// UpdateState sets the "state" field to the value that was provided on create.
func (u *EgressRouteUpsert) UpdateState() *EgressRouteUpsert {
	u.SetExcluded(egressroute.FieldState)
	return u
}

// SetLastObservedIP sets the "last_observed_ip" field.
func (u *EgressRouteUpsert) SetLastObservedIP(v string) *EgressRouteUpsert {
	u.Set(egressroute.FieldLastObservedIP, v)
	return u
}

// UpdateLastObservedIP sets the "last_observed_ip" field to the value that was provided on create.
func (u *EgressRouteUpsert) UpdateLastObservedIP() *EgressRouteUpsert {
	u.SetExcluded(egressroute.FieldLastObservedIP)
	return u
}

// ClearLastObservedIP clears the value of the "last_observed_ip" field.
func (u *EgressRouteUpsert) ClearLastObservedIP() *EgressRouteUpsert {
	u.SetNull(egressroute.FieldLastObservedIP)
	return u
}

// SetLastProbedAt sets the "last_probed_at" field.
func (u *EgressRouteUpsert) SetLastProbedAt(v time.Time) *EgressRouteUpsert {
	u.Set(egressroute.FieldLastProbedAt, v)
	return u
}

// UpdateLastProbedAt sets the "last_probed_at" field to the value that was provided on create.
func (u *EgressRouteUpsert) UpdateLastProbedAt() *EgressRouteUpsert {
	u.SetExcluded(egressroute.FieldLastProbedAt)
	return u
}

// ClearLastProbedAt clears the value of the "last_probed_at" field.
func (u *EgressRouteUpsert) ClearLastProbedAt() *EgressRouteUpsert {
	u.SetNull(egressroute.FieldLastProbedAt)
	return u
}

// SetVerifiedAt sets the "verified_at" field.
func (u *EgressRouteUpsert) SetVerifiedAt(v time.Time) *EgressRouteUpsert {
	u.Set(egressroute.FieldVerifiedAt, v)
	return u
}

// UpdateVerifiedAt sets the "verified_at" field to the value that was provided on create.
func (u *EgressRouteUpsert) UpdateVerifiedAt() *EgressRouteUpsert {
	u.SetExcluded(egressroute.FieldVerifiedAt)
	return u
}

// ClearVerifiedAt clears the value of the "verified_at" field.
func (u *EgressRouteUpsert) ClearVerifiedAt() *EgressRouteUpsert {
	u.SetNull(egressroute.FieldVerifiedAt)
	return u
}

// SetRevision sets the "revision" field.
func (u *EgressRouteUpsert) SetRevision(v int64) *EgressRouteUpsert {
	u.Set(egressroute.FieldRevision, v)
	return u
}

// UpdateRevision sets the "revision" field to the value that was provided on create.
func (u *EgressRouteUpsert) UpdateRevision() *EgressRouteUpsert {
	u.SetExcluded(egressroute.FieldRevision)
	return u
}

// AddRevision adds v to the "revision" field.
func (u *EgressRouteUpsert) AddRevision(v int64) *EgressRouteUpsert {
	u.Add(egressroute.FieldRevision, v)
	return u
}

// SetLastError sets the "last_error" field.
func (u *EgressRouteUpsert) SetLastError(v string) *EgressRouteUpsert {
	u.Set(egressroute.FieldLastError, v)
	return u
}

// UpdateLastError sets the "last_error" field to the value that was provided on create.
func (u *EgressRouteUpsert) UpdateLastError() *EgressRouteUpsert {
	u.SetExcluded(egressroute.FieldLastError)
	return u
}

// ClearLastError clears the value of the "last_error" field.
func (u *EgressRouteUpsert) ClearLastError() *EgressRouteUpsert {
	u.SetNull(egressroute.FieldLastError)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.EgressRoute.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *EgressRouteUpsertOne) UpdateNewValues() *EgressRouteUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(egressroute.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.EgressRoute.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *EgressRouteUpsertOne) Ignore() *EgressRouteUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *EgressRouteUpsertOne) DoNothing() *EgressRouteUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the EgressRouteCreate.OnConflict
// documentation for more info.
func (u *EgressRouteUpsertOne) Update(set func(*EgressRouteUpsert)) *EgressRouteUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&EgressRouteUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *EgressRouteUpsertOne) SetUpdatedAt(v time.Time) *EgressRouteUpsertOne {
	return u.Update(func(s *EgressRouteUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *EgressRouteUpsertOne) UpdateUpdatedAt() *EgressRouteUpsertOne {
	return u.Update(func(s *EgressRouteUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetKind sets the "kind" field.
func (u *EgressRouteUpsertOne) SetKind(v egressroute.Kind) *EgressRouteUpsertOne {
	return u.Update(func(s *EgressRouteUpsert) {
		s.SetKind(v)
	})
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *EgressRouteUpsertOne) UpdateKind() *EgressRouteUpsertOne {
	return u.Update(func(s *EgressRouteUpsert) {
		s.UpdateKind()
	})
}

// SetProxyID sets the "proxy_id" field.
func (u *EgressRouteUpsertOne) SetProxyID(v int64) *EgressRouteUpsertOne {
	return u.Update(func(s *EgressRouteUpsert) {
		s.SetProxyID(v)
	})
}

// UpdateProxyID sets the "proxy_id" field to the value that was provided on create.
func (u *EgressRouteUpsertOne) UpdateProxyID() *EgressRouteUpsertOne {
	return u.Update(func(s *EgressRouteUpsert) {
		s.UpdateProxyID()
	})
}

// ClearProxyID clears the value of the "proxy_id" field.
func (u *EgressRouteUpsertOne) ClearProxyID() *EgressRouteUpsertOne {
	return u.Update(func(s *EgressRouteUpsert) {
		s.ClearProxyID()
	})
}

// SetRuntimeScope sets the "runtime_scope" field.
func (u *EgressRouteUpsertOne) SetRuntimeScope(v string) *EgressRouteUpsertOne {
	return u.Update(func(s *EgressRouteUpsert) {
		s.SetRuntimeScope(v)
	})
}

// UpdateRuntimeScope sets the "runtime_scope" field to the value that was provided on create.
func (u *EgressRouteUpsertOne) UpdateRuntimeScope() *EgressRouteUpsertOne {
	return u.Update(func(s *EgressRouteUpsert) {
		s.UpdateRuntimeScope()
	})
}

// ClearRuntimeScope clears the value of the "runtime_scope" field.
func (u *EgressRouteUpsertOne) ClearRuntimeScope() *EgressRouteUpsertOne {
	return u.Update(func(s *EgressRouteUpsert) {
		s.ClearRuntimeScope()
	})
}

// SetExpectedIdentityID sets the "expected_identity_id" field.
func (u *EgressRouteUpsertOne) SetExpectedIdentityID(v int64) *EgressRouteUpsertOne {
	return u.Update(func(s *EgressRouteUpsert) {
		s.SetExpectedIdentityID(v)
	})
}

// UpdateExpectedIdentityID sets the "expected_identity_id" field to the value that was provided on create.
func (u *EgressRouteUpsertOne) UpdateExpectedIdentityID() *EgressRouteUpsertOne {
	return u.Update(func(s *EgressRouteUpsert) {
		s.UpdateExpectedIdentityID()
	})
}

// ClearExpectedIdentityID clears the value of the "expected_identity_id" field.
func (u *EgressRouteUpsertOne) ClearExpectedIdentityID() *EgressRouteUpsertOne {
	return u.Update(func(s *EgressRouteUpsert) {
		s.ClearExpectedIdentityID()
	})
}

// SetState sets the "state" field.
func (u *EgressRouteUpsertOne) SetState(v egressroute.State) *EgressRouteUpsertOne {
	return u.Update(func(s *EgressRouteUpsert) {
		s.SetState(v)
	})
}

// UpdateState sets the "state" field to the value that was provided on create.
func (u *EgressRouteUpsertOne) UpdateState() *EgressRouteUpsertOne {
	return u.Update(func(s *EgressRouteUpsert) {
		s.UpdateState()
	})
}

// SetLastObservedIP sets the "last_observed_ip" field.
func (u *EgressRouteUpsertOne) SetLastObservedIP(v string) *EgressRouteUpsertOne {
	return u.Update(func(s *EgressRouteUpsert) {
		s.SetLastObservedIP(v)
	})
}

// UpdateLastObservedIP sets the "last_observed_ip" field to the value that was provided on create.
func (u *EgressRouteUpsertOne) UpdateLastObservedIP() *EgressRouteUpsertOne {
	return u.Update(func(s *EgressRouteUpsert) {
		s.UpdateLastObservedIP()
	})
}

// ClearLastObservedIP clears the value of the "last_observed_ip" field.
func (u *EgressRouteUpsertOne) ClearLastObservedIP() *EgressRouteUpsertOne {
	return u.Update(func(s *EgressRouteUpsert) {
		s.ClearLastObservedIP()
	})
}

// SetLastProbedAt sets the "last_probed_at" field.
func (u *EgressRouteUpsertOne) SetLastProbedAt(v time.Time) *EgressRouteUpsertOne {
	return u.Update(func(s *EgressRouteUpsert) {
		s.SetLastProbedAt(v)
	})
}

// UpdateLastProbedAt sets the "last_probed_at" field to the value that was provided on create.
func (u *EgressRouteUpsertOne) UpdateLastProbedAt() *EgressRouteUpsertOne {
	return u.Update(func(s *EgressRouteUpsert) {
		s.UpdateLastProbedAt()
	})
}

// ClearLastProbedAt clears the value of the "last_probed_at" field.
func (u *EgressRouteUpsertOne) ClearLastProbedAt() *EgressRouteUpsertOne {
	return u.Update(func(s *EgressRouteUpsert) {
		s.ClearLastProbedAt()
	})
}

// SetVerifiedAt sets the "verified_at" field.
func (u *EgressRouteUpsertOne) SetVerifiedAt(v time.Time) *EgressRouteUpsertOne {
	return u.Update(func(s *EgressRouteUpsert) {
		s.SetVerifiedAt(v)
	})
}

// UpdateVerifiedAt sets the "verified_at" field to the value that was provided on create.
func (u *EgressRouteUpsertOne) UpdateVerifiedAt() *EgressRouteUpsertOne {
	return u.Update(func(s *EgressRouteUpsert) {
		s.UpdateVerifiedAt()
	})
}

// ClearVerifiedAt clears the value of the "verified_at" field.
func (u *EgressRouteUpsertOne) ClearVerifiedAt() *EgressRouteUpsertOne {
	return u.Update(func(s *EgressRouteUpsert) {
		s.ClearVerifiedAt()
	})
}

// SetRevision sets the "revision" field.
func (u *EgressRouteUpsertOne) SetRevision(v int64) *EgressRouteUpsertOne {
	return u.Update(func(s *EgressRouteUpsert) {
		s.SetRevision(v)
	})
}

// AddRevision adds v to the "revision" field.
func (u *EgressRouteUpsertOne) AddRevision(v int64) *EgressRouteUpsertOne {
	return u.Update(func(s *EgressRouteUpsert) {
		s.AddRevision(v)
	})
}

// UpdateRevision sets the "revision" field to the value that was provided on create.
func (u *EgressRouteUpsertOne) UpdateRevision() *EgressRouteUpsertOne {
	return u.Update(func(s *EgressRouteUpsert) {
		s.UpdateRevision()
	})
}

// SetLastError sets the "last_error" field.
func (u *EgressRouteUpsertOne) SetLastError(v string) *EgressRouteUpsertOne {
	return u.Update(func(s *EgressRouteUpsert) {
		s.SetLastError(v)
	})
}

// UpdateLastError sets the "last_error" field to the value that was provided on create.
func (u *EgressRouteUpsertOne) UpdateLastError() *EgressRouteUpsertOne {
	return u.Update(func(s *EgressRouteUpsert) {
		s.UpdateLastError()
	})
}

// ClearLastError clears the value of the "last_error" field.
func (u *EgressRouteUpsertOne) ClearLastError() *EgressRouteUpsertOne {
	return u.Update(func(s *EgressRouteUpsert) {
		s.ClearLastError()
	})
}

// Exec executes the query.
func (u *EgressRouteUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for EgressRouteCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *EgressRouteUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *EgressRouteUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *EgressRouteUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// EgressRouteCreateBulk is the builder for creating many EgressRoute entities in bulk.
type EgressRouteCreateBulk struct {
	config
	err      error
	builders []*EgressRouteCreate
	conflict []sql.ConflictOption
}

// Save creates the EgressRoute entities in the database.
func (_c *EgressRouteCreateBulk) Save(ctx context.Context) ([]*EgressRoute, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*EgressRoute, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*EgressRouteMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *EgressRouteCreateBulk) SaveX(ctx context.Context) []*EgressRoute {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EgressRouteCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EgressRouteCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.EgressRoute.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.EgressRouteUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *EgressRouteCreateBulk) OnConflict(opts ...sql.ConflictOption) *EgressRouteUpsertBulk {
	_c.conflict = opts
	return &EgressRouteUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.EgressRoute.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *EgressRouteCreateBulk) OnConflictColumns(columns ...string) *EgressRouteUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &EgressRouteUpsertBulk{
		create: _c,
	}
}

// EgressRouteUpsertBulk is the builder for "upsert"-ing
// a bulk of EgressRoute nodes.
type EgressRouteUpsertBulk struct {
	create *EgressRouteCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.EgressRoute.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *EgressRouteUpsertBulk) UpdateNewValues() *EgressRouteUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(egressroute.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.EgressRoute.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *EgressRouteUpsertBulk) Ignore() *EgressRouteUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *EgressRouteUpsertBulk) DoNothing() *EgressRouteUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the EgressRouteCreateBulk.OnConflict
// documentation for more info.
func (u *EgressRouteUpsertBulk) Update(set func(*EgressRouteUpsert)) *EgressRouteUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&EgressRouteUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *EgressRouteUpsertBulk) SetUpdatedAt(v time.Time) *EgressRouteUpsertBulk {
	return u.Update(func(s *EgressRouteUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *EgressRouteUpsertBulk) UpdateUpdatedAt() *EgressRouteUpsertBulk {
	return u.Update(func(s *EgressRouteUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetKind sets the "kind" field.
func (u *EgressRouteUpsertBulk) SetKind(v egressroute.Kind) *EgressRouteUpsertBulk {
	return u.Update(func(s *EgressRouteUpsert) {
		s.SetKind(v)
	})
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *EgressRouteUpsertBulk) UpdateKind() *EgressRouteUpsertBulk {
	return u.Update(func(s *EgressRouteUpsert) {
		s.UpdateKind()
	})
}

// SetProxyID sets the "proxy_id" field.
func (u *EgressRouteUpsertBulk) SetProxyID(v int64) *EgressRouteUpsertBulk {
	return u.Update(func(s *EgressRouteUpsert) {
		s.SetProxyID(v)
	})
}

// UpdateProxyID sets the "proxy_id" field to the value that was provided on create.
func (u *EgressRouteUpsertBulk) UpdateProxyID() *EgressRouteUpsertBulk {
	return u.Update(func(s *EgressRouteUpsert) {
		s.UpdateProxyID()
	})
}

// ClearProxyID clears the value of the "proxy_id" field.
func (u *EgressRouteUpsertBulk) ClearProxyID() *EgressRouteUpsertBulk {
	return u.Update(func(s *EgressRouteUpsert) {
		s.ClearProxyID()
	})
}

// SetRuntimeScope sets the "runtime_scope" field.
func (u *EgressRouteUpsertBulk) SetRuntimeScope(v string) *EgressRouteUpsertBulk {
	return u.Update(func(s *EgressRouteUpsert) {
		s.SetRuntimeScope(v)
	})
}

// UpdateRuntimeScope sets the "runtime_scope" field to the value that was provided on create.
func (u *EgressRouteUpsertBulk) UpdateRuntimeScope() *EgressRouteUpsertBulk {
	return u.Update(func(s *EgressRouteUpsert) {
		s.UpdateRuntimeScope()
	})
}

// ClearRuntimeScope clears the value of the "runtime_scope" field.
func (u *EgressRouteUpsertBulk) ClearRuntimeScope() *EgressRouteUpsertBulk {
	return u.Update(func(s *EgressRouteUpsert) {
		s.ClearRuntimeScope()
	})
}

// SetExpectedIdentityID sets the "expected_identity_id" field.
func (u *EgressRouteUpsertBulk) SetExpectedIdentityID(v int64) *EgressRouteUpsertBulk {
	return u.Update(func(s *EgressRouteUpsert) {
		s.SetExpectedIdentityID(v)
	})
}

// UpdateExpectedIdentityID sets the "expected_identity_id" field to the value that was provided on create.
func (u *EgressRouteUpsertBulk) UpdateExpectedIdentityID() *EgressRouteUpsertBulk {
	return u.Update(func(s *EgressRouteUpsert) {
		s.UpdateExpectedIdentityID()
	})
}

// ClearExpectedIdentityID clears the value of the "expected_identity_id" field.
func (u *EgressRouteUpsertBulk) ClearExpectedIdentityID() *EgressRouteUpsertBulk {
	return u.Update(func(s *EgressRouteUpsert) {
		s.ClearExpectedIdentityID()
	})
}

// SetState sets the "state" field.
func (u *EgressRouteUpsertBulk) SetState(v egressroute.State) *EgressRouteUpsertBulk {
	return u.Update(func(s *EgressRouteUpsert) {
		s.SetState(v)
	})
}

// UpdateState sets the "state" field to the value that was provided on create.
func (u *EgressRouteUpsertBulk) UpdateState() *EgressRouteUpsertBulk {
	return u.Update(func(s *EgressRouteUpsert) {
		s.UpdateState()
	})
}

// SetLastObservedIP sets the "last_observed_ip" field.
func (u *EgressRouteUpsertBulk) SetLastObservedIP(v string) *EgressRouteUpsertBulk {
	return u.Update(func(s *EgressRouteUpsert) {
		s.SetLastObservedIP(v)
	})
}

// UpdateLastObservedIP sets the "last_observed_ip" field to the value that was provided on create.
func (u *EgressRouteUpsertBulk) UpdateLastObservedIP() *EgressRouteUpsertBulk {
	return u.Update(func(s *EgressRouteUpsert) {
		s.UpdateLastObservedIP()
	})
}

// ClearLastObservedIP clears the value of the "last_observed_ip" field.
func (u *EgressRouteUpsertBulk) ClearLastObservedIP() *EgressRouteUpsertBulk {
	return u.Update(func(s *EgressRouteUpsert) {
		s.ClearLastObservedIP()
	})
}

// SetLastProbedAt sets the "last_probed_at" field.
func (u *EgressRouteUpsertBulk) SetLastProbedAt(v time.Time) *EgressRouteUpsertBulk {
	return u.Update(func(s *EgressRouteUpsert) {
		s.SetLastProbedAt(v)
	})
}

// UpdateLastProbedAt sets the "last_probed_at" field to the value that was provided on create.
func (u *EgressRouteUpsertBulk) UpdateLastProbedAt() *EgressRouteUpsertBulk {
	return u.Update(func(s *EgressRouteUpsert) {
		s.UpdateLastProbedAt()
	})
}

// ClearLastProbedAt clears the value of the "last_probed_at" field.
func (u *EgressRouteUpsertBulk) ClearLastProbedAt() *EgressRouteUpsertBulk {
	return u.Update(func(s *EgressRouteUpsert) {
		s.ClearLastProbedAt()
	})
}

// SetVerifiedAt sets the "verified_at" field.
func (u *EgressRouteUpsertBulk) SetVerifiedAt(v time.Time) *EgressRouteUpsertBulk {
	return u.Update(func(s *EgressRouteUpsert) {
		s.SetVerifiedAt(v)
	})
}

// UpdateVerifiedAt sets the "verified_at" field to the value that was provided on create.
func (u *EgressRouteUpsertBulk) UpdateVerifiedAt() *EgressRouteUpsertBulk {
	return u.Update(func(s *EgressRouteUpsert) {
		s.UpdateVerifiedAt()
	})
}

// ClearVerifiedAt clears the value of the "verified_at" field.
func (u *EgressRouteUpsertBulk) ClearVerifiedAt() *EgressRouteUpsertBulk {
	return u.Update(func(s *EgressRouteUpsert) {
		s.ClearVerifiedAt()
	})
}

// SetRevision sets the "revision" field.
func (u *EgressRouteUpsertBulk) SetRevision(v int64) *EgressRouteUpsertBulk {
	return u.Update(func(s *EgressRouteUpsert) {
		s.SetRevision(v)
	})
}

// AddRevision adds v to the "revision" field.
func (u *EgressRouteUpsertBulk) AddRevision(v int64) *EgressRouteUpsertBulk {
	return u.Update(func(s *EgressRouteUpsert) {
		s.AddRevision(v)
	})
}

// UpdateRevision sets the "revision" field to the value that was provided on create.
func (u *EgressRouteUpsertBulk) UpdateRevision() *EgressRouteUpsertBulk {
	return u.Update(func(s *EgressRouteUpsert) {
		s.UpdateRevision()
	})
}

// SetLastError sets the "last_error" field.
func (u *EgressRouteUpsertBulk) SetLastError(v string) *EgressRouteUpsertBulk {
	return u.Update(func(s *EgressRouteUpsert) {
		s.SetLastError(v)
	})
}

// UpdateLastError sets the "last_error" field to the value that was provided on create.
func (u *EgressRouteUpsertBulk) UpdateLastError() *EgressRouteUpsertBulk {
	return u.Update(func(s *EgressRouteUpsert) {
		s.UpdateLastError()
	})
}

// ClearLastError clears the value of the "last_error" field.
func (u *EgressRouteUpsertBulk) ClearLastError() *EgressRouteUpsertBulk {
	return u.Update(func(s *EgressRouteUpsert) {
		s.ClearLastError()
	})
}

// Exec executes the query.
func (u *EgressRouteUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the EgressRouteCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for EgressRouteCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *EgressRouteUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
