// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/egressidentity"
)

// EgressIdentity is the model entity for the EgressIdentity schema.
type EgressIdentity struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// PublicIP holds the value of the "public_ip" field.
	PublicIP string `json:"public_ip,omitempty"`
	// Status holds the value of the "status" field.
	Status egressidentity.Status `json:"status,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the EgressIdentityQuery when eager-loading is set.
	Edges        EgressIdentityEdges `json:"edges"`
	selectValues sql.SelectValues
}

// EgressIdentityEdges holds the relations/edges for other nodes in the graph.
type EgressIdentityEdges struct {
	// Routes holds the value of the routes edge.
	Routes []*EgressRoute `json:"routes,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// RoutesOrErr returns the Routes value or an error if the edge
// was not loaded in eager-loading.
func (e EgressIdentityEdges) RoutesOrErr() ([]*EgressRoute, error) {
	if e.loadedTypes[0] {
		return e.Routes, nil
	}
	return nil, &NotLoadedError{edge: "routes"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*EgressIdentity) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case egressidentity.FieldID:
			values[i] = new(sql.NullInt64)
		case egressidentity.FieldPublicIP, egressidentity.FieldStatus:
			values[i] = new(sql.NullString)
		case egressidentity.FieldCreatedAt, egressidentity.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the EgressIdentity fields.
func (_m *EgressIdentity) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case egressidentity.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case egressidentity.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case egressidentity.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case egressidentity.FieldPublicIP:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field public_ip", values[i])
			} else if value.Valid {
				_m.PublicIP = value.String
			}
		case egressidentity.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = egressidentity.Status(value.String)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the EgressIdentity.
// This includes values selected through modifiers, order, etc.
func (_m *EgressIdentity) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryRoutes queries the "routes" edge of the EgressIdentity entity.
func (_m *EgressIdentity) QueryRoutes() *EgressRouteQuery {
	return NewEgressIdentityClient(_m.config).QueryRoutes(_m)
}

// Update returns a builder for updating this EgressIdentity.
// Note that you need to call EgressIdentity.Unwrap() before calling this method if this EgressIdentity
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *EgressIdentity) Update() *EgressIdentityUpdateOne {
	return NewEgressIdentityClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the EgressIdentity entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *EgressIdentity) Unwrap() *EgressIdentity {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: EgressIdentity is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *EgressIdentity) String() string {
	var builder strings.Builder
	builder.WriteString("EgressIdentity(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("public_ip=")
	builder.WriteString(_m.PublicIP)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteByte(')')
	return builder.String()
}

// EgressIdentities is a parsable slice of EgressIdentity.
type EgressIdentities []*EgressIdentity
