// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/account"
	"github.com/Wei-Shaw/sub2api/ent/egressidentity"
	"github.com/Wei-Shaw/sub2api/ent/egressroute"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/proxy"
)

// EgressRouteUpdate is the builder for updating EgressRoute entities.
type EgressRouteUpdate struct {
	config
	hooks    []Hook
	mutation *EgressRouteMutation
}

// Where appends a list predicates to the EgressRouteUpdate builder.
func (_u *EgressRouteUpdate) Where(ps ...predicate.EgressRoute) *EgressRouteUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *EgressRouteUpdate) SetUpdatedAt(v time.Time) *EgressRouteUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetKind sets the "kind" field.
func (_u *EgressRouteUpdate) SetKind(v egressroute.Kind) *EgressRouteUpdate {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *EgressRouteUpdate) SetNillableKind(v *egressroute.Kind) *EgressRouteUpdate {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetProxyID sets the "proxy_id" field.
func (_u *EgressRouteUpdate) SetProxyID(v int64) *EgressRouteUpdate {
	_u.mutation.SetProxyID(v)
	return _u
}

// SetNillableProxyID sets the "proxy_id" field if the given value is not nil.
func (_u *EgressRouteUpdate) SetNillableProxyID(v *int64) *EgressRouteUpdate {
	if v != nil {
		_u.SetProxyID(*v)
	}
	return _u
}

// ClearProxyID clears the value of the "proxy_id" field.
func (_u *EgressRouteUpdate) ClearProxyID() *EgressRouteUpdate {
	_u.mutation.ClearProxyID()
	return _u
}

// SetRuntimeScope sets the "runtime_scope" field.
func (_u *EgressRouteUpdate) SetRuntimeScope(v string) *EgressRouteUpdate {
	_u.mutation.SetRuntimeScope(v)
	return _u
}

// SetNillableRuntimeScope sets the "runtime_scope" field if the given value is not nil.
func (_u *EgressRouteUpdate) SetNillableRuntimeScope(v *string) *EgressRouteUpdate {
	if v != nil {
		_u.SetRuntimeScope(*v)
	}
	return _u
}

// ClearRuntimeScope clears the value of the "runtime_scope" field.
func (_u *EgressRouteUpdate) ClearRuntimeScope() *EgressRouteUpdate {
	_u.mutation.ClearRuntimeScope()
	return _u
}

// SetExpectedIdentityID sets the "expected_identity_id" field.
func (_u *EgressRouteUpdate) SetExpectedIdentityID(v int64) *EgressRouteUpdate {
	_u.mutation.SetExpectedIdentityID(v)
	return _u
}

// SetNillableExpectedIdentityID sets the "expected_identity_id" field if the given value is not nil.
func (_u *EgressRouteUpdate) SetNillableExpectedIdentityID(v *int64) *EgressRouteUpdate {
	if v != nil {
		_u.SetExpectedIdentityID(*v)
	}
	return _u
}

// ClearExpectedIdentityID clears the value of the "expected_identity_id" field.
func (_u *EgressRouteUpdate) ClearExpectedIdentityID() *EgressRouteUpdate {
	_u.mutation.ClearExpectedIdentityID()
	return _u
}

// SetState sets the "state" field.
func (_u *EgressRouteUpdate) SetState(v egressroute.State) *EgressRouteUpdate {
	_u.mutation.SetState(v)
	return _u
}

// SetNillableState sets the "state" field if the given value is not nil.
func (_u *EgressRouteUpdate) SetNillableState(v *egressroute.State) *EgressRouteUpdate {
	if v != nil {
		_u.SetState(*v)
	}
	return _u
}

// SetLastObservedIP sets the "last_observed_ip" field.
func (_u *EgressRouteUpdate) SetLastObservedIP(v string) *EgressRouteUpdate {
	_u.mutation.SetLastObservedIP(v)
	return _u
}

// SetNillableLastObservedIP sets the "last_observed_ip" field if the given value is not nil.
func (_u *EgressRouteUpdate) SetNillableLastObservedIP(v *string) *EgressRouteUpdate {
	if v != nil {
		_u.SetLastObservedIP(*v)
	}
	return _u
}

// ClearLastObservedIP clears the value of the "last_observed_ip" field.
func (_u *EgressRouteUpdate) ClearLastObservedIP() *EgressRouteUpdate {
	_u.mutation.ClearLastObservedIP()
	return _u
}

// SetLastProbedAt sets the "last_probed_at" field.
func (_u *EgressRouteUpdate) SetLastProbedAt(v time.Time) *EgressRouteUpdate {
	_u.mutation.SetLastProbedAt(v)
	return _u
}

// SetNillableLastProbedAt sets the "last_probed_at" field if the given value is not nil.
func (_u *EgressRouteUpdate) SetNillableLastProbedAt(v *time.Time) *EgressRouteUpdate {
	if v != nil {
		_u.SetLastProbedAt(*v)
	}
	return _u
}

// ClearLastProbedAt clears the value of the "last_probed_at" field.
func (_u *EgressRouteUpdate) ClearLastProbedAt() *EgressRouteUpdate {
	_u.mutation.ClearLastProbedAt()
	return _u
}

// SetVerifiedAt sets the "verified_at" field.
func (_u *EgressRouteUpdate) SetVerifiedAt(v time.Time) *EgressRouteUpdate {
	_u.mutation.SetVerifiedAt(v)
	return _u
}

// SetNillableVerifiedAt sets the "verified_at" field if the given value is not nil.
func (_u *EgressRouteUpdate) SetNillableVerifiedAt(v *time.Time) *EgressRouteUpdate {
	if v != nil {
		_u.SetVerifiedAt(*v)
	}
	return _u
}

// ClearVerifiedAt clears the value of the "verified_at" field.
func (_u *EgressRouteUpdate) ClearVerifiedAt() *EgressRouteUpdate {
	_u.mutation.ClearVerifiedAt()
	return _u
}

// SetRevision sets the "revision" field.
func (_u *EgressRouteUpdate) SetRevision(v int64) *EgressRouteUpdate {
	_u.mutation.ResetRevision()
	_u.mutation.SetRevision(v)
	return _u
}

// SetNillableRevision sets the "revision" field if the given value is not nil.
func (_u *EgressRouteUpdate) SetNillableRevision(v *int64) *EgressRouteUpdate {
	if v != nil {
		_u.SetRevision(*v)
	}
	return _u
}

// AddRevision adds value to the "revision" field.
func (_u *EgressRouteUpdate) AddRevision(v int64) *EgressRouteUpdate {
	_u.mutation.AddRevision(v)
	return _u
}

// SetLastError sets the "last_error" field.
func (_u *EgressRouteUpdate) SetLastError(v string) *EgressRouteUpdate {
	_u.mutation.SetLastError(v)
	return _u
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_u *EgressRouteUpdate) SetNillableLastError(v *string) *EgressRouteUpdate {
	if v != nil {
		_u.SetLastError(*v)
	}
	return _u
}

// ClearLastError clears the value of the "last_error" field.
func (_u *EgressRouteUpdate) ClearLastError() *EgressRouteUpdate {
	_u.mutation.ClearLastError()
	return _u
}

// SetProxy sets the "proxy" edge to the Proxy entity.
func (_u *EgressRouteUpdate) SetProxy(v *Proxy) *EgressRouteUpdate {
	return _u.SetProxyID(v.ID)
}

// SetExpectedIdentity sets the "expected_identity" edge to the EgressIdentity entity.
func (_u *EgressRouteUpdate) SetExpectedIdentity(v *EgressIdentity) *EgressRouteUpdate {
	return _u.SetExpectedIdentityID(v.ID)
}

// AddAccountIDs adds the "accounts" edge to the Account entity by IDs.
func (_u *EgressRouteUpdate) AddAccountIDs(ids ...int64) *EgressRouteUpdate {
	_u.mutation.AddAccountIDs(ids...)
	return _u
}

// AddAccounts adds the "accounts" edges to the Account entity.
func (_u *EgressRouteUpdate) AddAccounts(v ...*Account) *EgressRouteUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAccountIDs(ids...)
}

// Mutation returns the EgressRouteMutation object of the builder.
func (_u *EgressRouteUpdate) Mutation() *EgressRouteMutation {
	return _u.mutation
}

// ClearProxy clears the "proxy" edge to the Proxy entity.
func (_u *EgressRouteUpdate) ClearProxy() *EgressRouteUpdate {
	_u.mutation.ClearProxy()
	return _u
}

// ClearExpectedIdentity clears the "expected_identity" edge to the EgressIdentity entity.
func (_u *EgressRouteUpdate) ClearExpectedIdentity() *EgressRouteUpdate {
	_u.mutation.ClearExpectedIdentity()
	return _u
}

// ClearAccounts clears all "accounts" edges to the Account entity.
func (_u *EgressRouteUpdate) ClearAccounts() *EgressRouteUpdate {
	_u.mutation.ClearAccounts()
	return _u
}

// RemoveAccountIDs removes the "accounts" edge to Account entities by IDs.
func (_u *EgressRouteUpdate) RemoveAccountIDs(ids ...int64) *EgressRouteUpdate {
	_u.mutation.RemoveAccountIDs(ids...)
	return _u
}

// RemoveAccounts removes "accounts" edges to Account entities.
func (_u *EgressRouteUpdate) RemoveAccounts(v ...*Account) *EgressRouteUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAccountIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *EgressRouteUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EgressRouteUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *EgressRouteUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EgressRouteUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *EgressRouteUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := egressroute.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *EgressRouteUpdate) check() error {
	if v, ok := _u.mutation.Kind(); ok {
		if err := egressroute.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "EgressRoute.kind": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RuntimeScope(); ok {
		if err := egressroute.RuntimeScopeValidator(v); err != nil {
			return &ValidationError{Name: "runtime_scope", err: fmt.Errorf(`ent: validator failed for field "EgressRoute.runtime_scope": %w`, err)}
		}
	}
	if v, ok := _u.mutation.State(); ok {
		if err := egressroute.StateValidator(v); err != nil {
			return &ValidationError{Name: "state", err: fmt.Errorf(`ent: validator failed for field "EgressRoute.state": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Revision(); ok {
		if err := egressroute.RevisionValidator(v); err != nil {
			return &ValidationError{Name: "revision", err: fmt.Errorf(`ent: validator failed for field "EgressRoute.revision": %w`, err)}
		}
	}
	return nil
}

func (_u *EgressRouteUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(egressroute.Table, egressroute.Columns, sqlgraph.NewFieldSpec(egressroute.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(egressroute.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(egressroute.FieldKind, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.RuntimeScope(); ok {
		_spec.SetField(egressroute.FieldRuntimeScope, field.TypeString, value)
	}
	if _u.mutation.RuntimeScopeCleared() {
		_spec.ClearField(egressroute.FieldRuntimeScope, field.TypeString)
	}
	if value, ok := _u.mutation.State(); ok {
		_spec.SetField(egressroute.FieldState, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.LastObservedIP(); ok {
		_spec.SetField(egressroute.FieldLastObservedIP, field.TypeString, value)
	}
	if _u.mutation.LastObservedIPCleared() {
		_spec.ClearField(egressroute.FieldLastObservedIP, field.TypeString)
	}
	if value, ok := _u.mutation.LastProbedAt(); ok {
		_spec.SetField(egressroute.FieldLastProbedAt, field.TypeTime, value)
	}
	if _u.mutation.LastProbedAtCleared() {
		_spec.ClearField(egressroute.FieldLastProbedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.VerifiedAt(); ok {
		_spec.SetField(egressroute.FieldVerifiedAt, field.TypeTime, value)
	}
	if _u.mutation.VerifiedAtCleared() {
		_spec.ClearField(egressroute.FieldVerifiedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Revision(); ok {
		_spec.SetField(egressroute.FieldRevision, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRevision(); ok {
		_spec.AddField(egressroute.FieldRevision, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.LastError(); ok {
		_spec.SetField(egressroute.FieldLastError, field.TypeString, value)
	}
	if _u.mutation.LastErrorCleared() {
		_spec.ClearField(egressroute.FieldLastError, field.TypeString)
	}
	if _u.mutation.ProxyCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   egressroute.ProxyTable,
			Columns: []string{egressroute.ProxyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(proxy.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProxyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   egressroute.ProxyTable,
			Columns: []string{egressroute.ProxyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(proxy.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ExpectedIdentityCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   egressroute.ExpectedIdentityTable,
			Columns: []string{egressroute.ExpectedIdentityColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(egressidentity.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ExpectedIdentityIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   egressroute.ExpectedIdentityTable,
			Columns: []string{egressroute.ExpectedIdentityColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(egressidentity.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AccountsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   egressroute.AccountsTable,
			Columns: egressroute.AccountsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		createE := &AccountEgressBindingCreate{config: _u.config, mutation: newAccountEgressBindingMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAccountsIDs(); len(nodes) > 0 && !_u.mutation.AccountsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   egressroute.AccountsTable,
			Columns: egressroute.AccountsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &AccountEgressBindingCreate{config: _u.config, mutation: newAccountEgressBindingMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AccountsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   egressroute.AccountsTable,
			Columns: egressroute.AccountsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &AccountEgressBindingCreate{config: _u.config, mutation: newAccountEgressBindingMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{egressroute.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// EgressRouteUpdateOne is the builder for updating a single EgressRoute entity.
type EgressRouteUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *EgressRouteMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *EgressRouteUpdateOne) SetUpdatedAt(v time.Time) *EgressRouteUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetKind sets the "kind" field.
func (_u *EgressRouteUpdateOne) SetKind(v egressroute.Kind) *EgressRouteUpdateOne {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *EgressRouteUpdateOne) SetNillableKind(v *egressroute.Kind) *EgressRouteUpdateOne {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetProxyID sets the "proxy_id" field.
func (_u *EgressRouteUpdateOne) SetProxyID(v int64) *EgressRouteUpdateOne {
	_u.mutation.SetProxyID(v)
	return _u
}

// SetNillableProxyID sets the "proxy_id" field if the given value is not nil.
func (_u *EgressRouteUpdateOne) SetNillableProxyID(v *int64) *EgressRouteUpdateOne {
	if v != nil {
		_u.SetProxyID(*v)
	}
	return _u
}

// ClearProxyID clears the value of the "proxy_id" field.
func (_u *EgressRouteUpdateOne) ClearProxyID() *EgressRouteUpdateOne {
	_u.mutation.ClearProxyID()
	return _u
}

// SetRuntimeScope sets the "runtime_scope" field.
func (_u *EgressRouteUpdateOne) SetRuntimeScope(v string) *EgressRouteUpdateOne {
	_u.mutation.SetRuntimeScope(v)
	return _u
}

// SetNillableRuntimeScope sets the "runtime_scope" field if the given value is not nil.
func (_u *EgressRouteUpdateOne) SetNillableRuntimeScope(v *string) *EgressRouteUpdateOne {
	if v != nil {
		_u.SetRuntimeScope(*v)
	}
	return _u
}

// ClearRuntimeScope clears the value of the "runtime_scope" field.
func (_u *EgressRouteUpdateOne) ClearRuntimeScope() *EgressRouteUpdateOne {
	_u.mutation.ClearRuntimeScope()
	return _u
}

// SetExpectedIdentityID sets the "expected_identity_id" field.
func (_u *EgressRouteUpdateOne) SetExpectedIdentityID(v int64) *EgressRouteUpdateOne {
	_u.mutation.SetExpectedIdentityID(v)
	return _u
}

// SetNillableExpectedIdentityID sets the "expected_identity_id" field if the given value is not nil.
func (_u *EgressRouteUpdateOne) SetNillableExpectedIdentityID(v *int64) *EgressRouteUpdateOne {
	if v != nil {
		_u.SetExpectedIdentityID(*v)
	}
	return _u
}

// ClearExpectedIdentityID clears the value of the "expected_identity_id" field.
func (_u *EgressRouteUpdateOne) ClearExpectedIdentityID() *EgressRouteUpdateOne {
	_u.mutation.ClearExpectedIdentityID()
	return _u
}

// SetState sets the "state" field.
func (_u *EgressRouteUpdateOne) SetState(v egressroute.State) *EgressRouteUpdateOne {
	_u.mutation.SetState(v)
	return _u
}

// SetNillableState sets the "state" field if the given value is not nil.
func (_u *EgressRouteUpdateOne) SetNillableState(v *egressroute.State) *EgressRouteUpdateOne {
	if v != nil {
		_u.SetState(*v)
	}
	return _u
}

// SetLastObservedIP sets the "last_observed_ip" field.
func (_u *EgressRouteUpdateOne) SetLastObservedIP(v string) *EgressRouteUpdateOne {
	_u.mutation.SetLastObservedIP(v)
	return _u
}

// SetNillableLastObservedIP sets the "last_observed_ip" field if the given value is not nil.
func (_u *EgressRouteUpdateOne) SetNillableLastObservedIP(v *string) *EgressRouteUpdateOne {
	if v != nil {
		_u.SetLastObservedIP(*v)
	}
	return _u
}

// ClearLastObservedIP clears the value of the "last_observed_ip" field.
func (_u *EgressRouteUpdateOne) ClearLastObservedIP() *EgressRouteUpdateOne {
	_u.mutation.ClearLastObservedIP()
	return _u
}

// SetLastProbedAt sets the "last_probed_at" field.
func (_u *EgressRouteUpdateOne) SetLastProbedAt(v time.Time) *EgressRouteUpdateOne {
	_u.mutation.SetLastProbedAt(v)
	return _u
}

// SetNillableLastProbedAt sets the "last_probed_at" field if the given value is not nil.
func (_u *EgressRouteUpdateOne) SetNillableLastProbedAt(v *time.Time) *EgressRouteUpdateOne {
	if v != nil {
		_u.SetLastProbedAt(*v)
	}
	return _u
}

// ClearLastProbedAt clears the value of the "last_probed_at" field.
func (_u *EgressRouteUpdateOne) ClearLastProbedAt() *EgressRouteUpdateOne {
	_u.mutation.ClearLastProbedAt()
	return _u
}

// SetVerifiedAt sets the "verified_at" field.
func (_u *EgressRouteUpdateOne) SetVerifiedAt(v time.Time) *EgressRouteUpdateOne {
	_u.mutation.SetVerifiedAt(v)
	return _u
}

// SetNillableVerifiedAt sets the "verified_at" field if the given value is not nil.
func (_u *EgressRouteUpdateOne) SetNillableVerifiedAt(v *time.Time) *EgressRouteUpdateOne {
	if v != nil {
		_u.SetVerifiedAt(*v)
	}
	return _u
}

// ClearVerifiedAt clears the value of the "verified_at" field.
func (_u *EgressRouteUpdateOne) ClearVerifiedAt() *EgressRouteUpdateOne {
	_u.mutation.ClearVerifiedAt()
	return _u
}

// SetRevision sets the "revision" field.
func (_u *EgressRouteUpdateOne) SetRevision(v int64) *EgressRouteUpdateOne {
	_u.mutation.ResetRevision()
	_u.mutation.SetRevision(v)
	return _u
}

// SetNillableRevision sets the "revision" field if the given value is not nil.
func (_u *EgressRouteUpdateOne) SetNillableRevision(v *int64) *EgressRouteUpdateOne {
	if v != nil {
		_u.SetRevision(*v)
	}
	return _u
}

// AddRevision adds value to the "revision" field.
func (_u *EgressRouteUpdateOne) AddRevision(v int64) *EgressRouteUpdateOne {
	_u.mutation.AddRevision(v)
	return _u
}

// SetLastError sets the "last_error" field.
func (_u *EgressRouteUpdateOne) SetLastError(v string) *EgressRouteUpdateOne {
	_u.mutation.SetLastError(v)
	return _u
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_u *EgressRouteUpdateOne) SetNillableLastError(v *string) *EgressRouteUpdateOne {
	if v != nil {
		_u.SetLastError(*v)
	}
	return _u
}

// ClearLastError clears the value of the "last_error" field.
func (_u *EgressRouteUpdateOne) ClearLastError() *EgressRouteUpdateOne {
	_u.mutation.ClearLastError()
	return _u
}

// SetProxy sets the "proxy" edge to the Proxy entity.
func (_u *EgressRouteUpdateOne) SetProxy(v *Proxy) *EgressRouteUpdateOne {
	return _u.SetProxyID(v.ID)
}

// SetExpectedIdentity sets the "expected_identity" edge to the EgressIdentity entity.
func (_u *EgressRouteUpdateOne) SetExpectedIdentity(v *EgressIdentity) *EgressRouteUpdateOne {
	return _u.SetExpectedIdentityID(v.ID)
}

// AddAccountIDs adds the "accounts" edge to the Account entity by IDs.
func (_u *EgressRouteUpdateOne) AddAccountIDs(ids ...int64) *EgressRouteUpdateOne {
	_u.mutation.AddAccountIDs(ids...)
	return _u
}

// AddAccounts adds the "accounts" edges to the Account entity.
func (_u *EgressRouteUpdateOne) AddAccounts(v ...*Account) *EgressRouteUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAccountIDs(ids...)
}

// Mutation returns the EgressRouteMutation object of the builder.
func (_u *EgressRouteUpdateOne) Mutation() *EgressRouteMutation {
	return _u.mutation
}

// ClearProxy clears the "proxy" edge to the Proxy entity.
func (_u *EgressRouteUpdateOne) ClearProxy() *EgressRouteUpdateOne {
	_u.mutation.ClearProxy()
	return _u
}

// ClearExpectedIdentity clears the "expected_identity" edge to the EgressIdentity entity.
func (_u *EgressRouteUpdateOne) ClearExpectedIdentity() *EgressRouteUpdateOne {
	_u.mutation.ClearExpectedIdentity()
	return _u
}

// ClearAccounts clears all "accounts" edges to the Account entity.
func (_u *EgressRouteUpdateOne) ClearAccounts() *EgressRouteUpdateOne {
	_u.mutation.ClearAccounts()
	return _u
}

// RemoveAccountIDs removes the "accounts" edge to Account entities by IDs.
func (_u *EgressRouteUpdateOne) RemoveAccountIDs(ids ...int64) *EgressRouteUpdateOne {
	_u.mutation.RemoveAccountIDs(ids...)
	return _u
}

// RemoveAccounts removes "accounts" edges to Account entities.
func (_u *EgressRouteUpdateOne) RemoveAccounts(v ...*Account) *EgressRouteUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAccountIDs(ids...)
}

// Where appends a list predicates to the EgressRouteUpdate builder.
func (_u *EgressRouteUpdateOne) Where(ps ...predicate.EgressRoute) *EgressRouteUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *EgressRouteUpdateOne) Select(field string, fields ...string) *EgressRouteUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated EgressRoute entity.
func (_u *EgressRouteUpdateOne) Save(ctx context.Context) (*EgressRoute, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EgressRouteUpdateOne) SaveX(ctx context.Context) *EgressRoute {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *EgressRouteUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EgressRouteUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *EgressRouteUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := egressroute.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *EgressRouteUpdateOne) check() error {
	if v, ok := _u.mutation.Kind(); ok {
		if err := egressroute.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "EgressRoute.kind": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RuntimeScope(); ok {
		if err := egressroute.RuntimeScopeValidator(v); err != nil {
			return &ValidationError{Name: "runtime_scope", err: fmt.Errorf(`ent: validator failed for field "EgressRoute.runtime_scope": %w`, err)}
		}
	}
	if v, ok := _u.mutation.State(); ok {
		if err := egressroute.StateValidator(v); err != nil {
			return &ValidationError{Name: "state", err: fmt.Errorf(`ent: validator failed for field "EgressRoute.state": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Revision(); ok {
		if err := egressroute.RevisionValidator(v); err != nil {
			return &ValidationError{Name: "revision", err: fmt.Errorf(`ent: validator failed for field "EgressRoute.revision": %w`, err)}
		}
	}
	return nil
}

func (_u *EgressRouteUpdateOne) sqlSave(ctx context.Context) (_node *EgressRoute, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(egressroute.Table, egressroute.Columns, sqlgraph.NewFieldSpec(egressroute.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "EgressRoute.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, egressroute.FieldID)
		for _, f := range fields {
			if !egressroute.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != egressroute.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(egressroute.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(egressroute.FieldKind, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.RuntimeScope(); ok {
		_spec.SetField(egressroute.FieldRuntimeScope, field.TypeString, value)
	}
	if _u.mutation.RuntimeScopeCleared() {
		_spec.ClearField(egressroute.FieldRuntimeScope, field.TypeString)
	}
	if value, ok := _u.mutation.State(); ok {
		_spec.SetField(egressroute.FieldState, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.LastObservedIP(); ok {
		_spec.SetField(egressroute.FieldLastObservedIP, field.TypeString, value)
	}
	if _u.mutation.LastObservedIPCleared() {
		_spec.ClearField(egressroute.FieldLastObservedIP, field.TypeString)
	}
	if value, ok := _u.mutation.LastProbedAt(); ok {
		_spec.SetField(egressroute.FieldLastProbedAt, field.TypeTime, value)
	}
	if _u.mutation.LastProbedAtCleared() {
		_spec.ClearField(egressroute.FieldLastProbedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.VerifiedAt(); ok {
		_spec.SetField(egressroute.FieldVerifiedAt, field.TypeTime, value)
	}
	if _u.mutation.VerifiedAtCleared() {
		_spec.ClearField(egressroute.FieldVerifiedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Revision(); ok {
		_spec.SetField(egressroute.FieldRevision, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRevision(); ok {
		_spec.AddField(egressroute.FieldRevision, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.LastError(); ok {
		_spec.SetField(egressroute.FieldLastError, field.TypeString, value)
	}
	if _u.mutation.LastErrorCleared() {
		_spec.ClearField(egressroute.FieldLastError, field.TypeString)
	}
	if _u.mutation.ProxyCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   egressroute.ProxyTable,
			Columns: []string{egressroute.ProxyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(proxy.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProxyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   egressroute.ProxyTable,
			Columns: []string{egressroute.ProxyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(proxy.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ExpectedIdentityCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   egressroute.ExpectedIdentityTable,
			Columns: []string{egressroute.ExpectedIdentityColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(egressidentity.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ExpectedIdentityIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   egressroute.ExpectedIdentityTable,
			Columns: []string{egressroute.ExpectedIdentityColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(egressidentity.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AccountsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   egressroute.AccountsTable,
			Columns: egressroute.AccountsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		createE := &AccountEgressBindingCreate{config: _u.config, mutation: newAccountEgressBindingMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAccountsIDs(); len(nodes) > 0 && !_u.mutation.AccountsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   egressroute.AccountsTable,
			Columns: egressroute.AccountsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &AccountEgressBindingCreate{config: _u.config, mutation: newAccountEgressBindingMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AccountsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   egressroute.AccountsTable,
			Columns: egressroute.AccountsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &AccountEgressBindingCreate{config: _u.config, mutation: newAccountEgressBindingMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &EgressRoute{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{egressroute.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
