// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/egressidentity"
	"github.com/Wei-Shaw/sub2api/ent/egressroute"
	"github.com/Wei-Shaw/sub2api/ent/proxy"
)

// EgressRoute is the model entity for the EgressRoute schema.
type EgressRoute struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Kind holds the value of the "kind" field.
	Kind egressroute.Kind `json:"kind,omitempty"`
	// ProxyID holds the value of the "proxy_id" field.
	ProxyID *int64 `json:"proxy_id,omitempty"`
	// RuntimeScope holds the value of the "runtime_scope" field.
	RuntimeScope *string `json:"runtime_scope,omitempty"`
	// ExpectedIdentityID holds the value of the "expected_identity_id" field.
	ExpectedIdentityID *int64 `json:"expected_identity_id,omitempty"`
	// State holds the value of the "state" field.
	State egressroute.State `json:"state,omitempty"`
	// LastObservedIP holds the value of the "last_observed_ip" field.
	LastObservedIP *string `json:"last_observed_ip,omitempty"`
	// LastProbedAt holds the value of the "last_probed_at" field.
	LastProbedAt *time.Time `json:"last_probed_at,omitempty"`
	// VerifiedAt holds the value of the "verified_at" field.
	VerifiedAt *time.Time `json:"verified_at,omitempty"`
	// Revision holds the value of the "revision" field.
	Revision int64 `json:"revision,omitempty"`
	// LastError holds the value of the "last_error" field.
	LastError *string `json:"last_error,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the EgressRouteQuery when eager-loading is set.
	Edges        EgressRouteEdges `json:"edges"`
	selectValues sql.SelectValues
}

// EgressRouteEdges holds the relations/edges for other nodes in the graph.
type EgressRouteEdges struct {
	// Proxy holds the value of the proxy edge.
	Proxy *Proxy `json:"proxy,omitempty"`
	// ExpectedIdentity holds the value of the expected_identity edge.
	ExpectedIdentity *EgressIdentity `json:"expected_identity,omitempty"`
	// Accounts holds the value of the accounts edge.
	Accounts []*Account `json:"accounts,omitempty"`
	// Bindings holds the value of the bindings edge.
	Bindings []*AccountEgressBinding `json:"bindings,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [4]bool
}

// ProxyOrErr returns the Proxy value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e EgressRouteEdges) ProxyOrErr() (*Proxy, error) {
	if e.Proxy != nil {
		return e.Proxy, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: proxy.Label}
	}
	return nil, &NotLoadedError{edge: "proxy"}
}

// ExpectedIdentityOrErr returns the ExpectedIdentity value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e EgressRouteEdges) ExpectedIdentityOrErr() (*EgressIdentity, error) {
	if e.ExpectedIdentity != nil {
		return e.ExpectedIdentity, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: egressidentity.Label}
	}
	return nil, &NotLoadedError{edge: "expected_identity"}
}

// AccountsOrErr returns the Accounts value or an error if the edge
// was not loaded in eager-loading.
func (e EgressRouteEdges) AccountsOrErr() ([]*Account, error) {
	if e.loadedTypes[2] {
		return e.Accounts, nil
	}
	return nil, &NotLoadedError{edge: "accounts"}
}

// BindingsOrErr returns the Bindings value or an error if the edge
// was not loaded in eager-loading.
func (e EgressRouteEdges) BindingsOrErr() ([]*AccountEgressBinding, error) {
	if e.loadedTypes[3] {
		return e.Bindings, nil
	}
	return nil, &NotLoadedError{edge: "bindings"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*EgressRoute) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case egressroute.FieldID, egressroute.FieldProxyID, egressroute.FieldExpectedIdentityID, egressroute.FieldRevision:
			values[i] = new(sql.NullInt64)
		case egressroute.FieldKind, egressroute.FieldRuntimeScope, egressroute.FieldState, egressroute.FieldLastObservedIP, egressroute.FieldLastError:
			values[i] = new(sql.NullString)
		case egressroute.FieldCreatedAt, egressroute.FieldUpdatedAt, egressroute.FieldLastProbedAt, egressroute.FieldVerifiedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the EgressRoute fields.
func (_m *EgressRoute) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case egressroute.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case egressroute.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case egressroute.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case egressroute.FieldKind:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field kind", values[i])
			} else if value.Valid {
				_m.Kind = egressroute.Kind(value.String)
			}
		case egressroute.FieldProxyID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field proxy_id", values[i])
			} else if value.Valid {
				_m.ProxyID = new(int64)
				*_m.ProxyID = value.Int64
			}
		case egressroute.FieldRuntimeScope:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field runtime_scope", values[i])
			} else if value.Valid {
				_m.RuntimeScope = new(string)
				*_m.RuntimeScope = value.String
			}
		case egressroute.FieldExpectedIdentityID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field expected_identity_id", values[i])
			} else if value.Valid {
				_m.ExpectedIdentityID = new(int64)
				*_m.ExpectedIdentityID = value.Int64
			}
		case egressroute.FieldState:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field state", values[i])
			} else if value.Valid {
				_m.State = egressroute.State(value.String)
			}
		case egressroute.FieldLastObservedIP:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field last_observed_ip", values[i])
			} else if value.Valid {
				_m.LastObservedIP = new(string)
				*_m.LastObservedIP = value.String
			}
		case egressroute.FieldLastProbedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_probed_at", values[i])
			} else if value.Valid {
				_m.LastProbedAt = new(time.Time)
				*_m.LastProbedAt = value.Time
			}
		case egressroute.FieldVerifiedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field verified_at", values[i])
			} else if value.Valid {
				_m.VerifiedAt = new(time.Time)
				*_m.VerifiedAt = value.Time
			}
		case egressroute.FieldRevision:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field revision", values[i])
			} else if value.Valid {
				_m.Revision = value.Int64
			}
		case egressroute.FieldLastError:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field last_error", values[i])
			} else if value.Valid {
				_m.LastError = new(string)
				*_m.LastError = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the EgressRoute.
// This includes values selected through modifiers, order, etc.
func (_m *EgressRoute) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryProxy queries the "proxy" edge of the EgressRoute entity.
func (_m *EgressRoute) QueryProxy() *ProxyQuery {
	return NewEgressRouteClient(_m.config).QueryProxy(_m)
}

// QueryExpectedIdentity queries the "expected_identity" edge of the EgressRoute entity.
func (_m *EgressRoute) QueryExpectedIdentity() *EgressIdentityQuery {
	return NewEgressRouteClient(_m.config).QueryExpectedIdentity(_m)
}

// QueryAccounts queries the "accounts" edge of the EgressRoute entity.
func (_m *EgressRoute) QueryAccounts() *AccountQuery {
	return NewEgressRouteClient(_m.config).QueryAccounts(_m)
}

// QueryBindings queries the "bindings" edge of the EgressRoute entity.
func (_m *EgressRoute) QueryBindings() *AccountEgressBindingQuery {
	return NewEgressRouteClient(_m.config).QueryBindings(_m)
}

// Update returns a builder for updating this EgressRoute.
// Note that you need to call EgressRoute.Unwrap() before calling this method if this EgressRoute
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *EgressRoute) Update() *EgressRouteUpdateOne {
	return NewEgressRouteClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the EgressRoute entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *EgressRoute) Unwrap() *EgressRoute {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: EgressRoute is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *EgressRoute) String() string {
	var builder strings.Builder
	builder.WriteString("EgressRoute(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("kind=")
	builder.WriteString(fmt.Sprintf("%v", _m.Kind))
	builder.WriteString(", ")
	if v := _m.ProxyID; v != nil {
		builder.WriteString("proxy_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.RuntimeScope; v != nil {
		builder.WriteString("runtime_scope=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ExpectedIdentityID; v != nil {
		builder.WriteString("expected_identity_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("state=")
	builder.WriteString(fmt.Sprintf("%v", _m.State))
	builder.WriteString(", ")
	if v := _m.LastObservedIP; v != nil {
		builder.WriteString("last_observed_ip=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.LastProbedAt; v != nil {
		builder.WriteString("last_probed_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.VerifiedAt; v != nil {
		builder.WriteString("verified_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("revision=")
	builder.WriteString(fmt.Sprintf("%v", _m.Revision))
	builder.WriteString(", ")
	if v := _m.LastError; v != nil {
		builder.WriteString("last_error=")
		builder.WriteString(*v)
	}
	builder.WriteByte(')')
	return builder.String()
}

// EgressRoutes is a parsable slice of EgressRoute.
type EgressRoutes []*EgressRoute
