// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/egressidentity"
	"github.com/Wei-Shaw/sub2api/ent/egressroute"
)

// EgressIdentityCreate is the builder for creating a EgressIdentity entity.
type EgressIdentityCreate struct {
	config
	mutation *EgressIdentityMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *EgressIdentityCreate) SetCreatedAt(v time.Time) *EgressIdentityCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *EgressIdentityCreate) SetNillableCreatedAt(v *time.Time) *EgressIdentityCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *EgressIdentityCreate) SetUpdatedAt(v time.Time) *EgressIdentityCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *EgressIdentityCreate) SetNillableUpdatedAt(v *time.Time) *EgressIdentityCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetPublicIP sets the "public_ip" field.
func (_c *EgressIdentityCreate) SetPublicIP(v string) *EgressIdentityCreate {
	_c.mutation.SetPublicIP(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *EgressIdentityCreate) SetStatus(v egressidentity.Status) *EgressIdentityCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *EgressIdentityCreate) SetNillableStatus(v *egressidentity.Status) *EgressIdentityCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// AddRouteIDs adds the "routes" edge to the EgressRoute entity by IDs.
func (_c *EgressIdentityCreate) AddRouteIDs(ids ...int64) *EgressIdentityCreate {
	_c.mutation.AddRouteIDs(ids...)
	return _c
}

// AddRoutes adds the "routes" edges to the EgressRoute entity.
func (_c *EgressIdentityCreate) AddRoutes(v ...*EgressRoute) *EgressIdentityCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddRouteIDs(ids...)
}

// Mutation returns the EgressIdentityMutation object of the builder.
func (_c *EgressIdentityCreate) Mutation() *EgressIdentityMutation {
	return _c.mutation
}

// Save creates the EgressIdentity in the database.
func (_c *EgressIdentityCreate) Save(ctx context.Context) (*EgressIdentity, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *EgressIdentityCreate) SaveX(ctx context.Context) *EgressIdentity {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EgressIdentityCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EgressIdentityCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *EgressIdentityCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := egressidentity.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := egressidentity.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := egressidentity.DefaultStatus
		_c.mutation.SetStatus(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *EgressIdentityCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "EgressIdentity.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "EgressIdentity.updated_at"`)}
	}
	if _, ok := _c.mutation.PublicIP(); !ok {
		return &ValidationError{Name: "public_ip", err: errors.New(`ent: missing required field "EgressIdentity.public_ip"`)}
	}
	if v, ok := _c.mutation.PublicIP(); ok {
		if err := egressidentity.PublicIPValidator(v); err != nil {
			return &ValidationError{Name: "public_ip", err: fmt.Errorf(`ent: validator failed for field "EgressIdentity.public_ip": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "EgressIdentity.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := egressidentity.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "EgressIdentity.status": %w`, err)}
		}
	}
	return nil
}

func (_c *EgressIdentityCreate) sqlSave(ctx context.Context) (*EgressIdentity, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *EgressIdentityCreate) createSpec() (*EgressIdentity, *sqlgraph.CreateSpec) {
	var (
		_node = &EgressIdentity{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(egressidentity.Table, sqlgraph.NewFieldSpec(egressidentity.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(egressidentity.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(egressidentity.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.PublicIP(); ok {
		_spec.SetField(egressidentity.FieldPublicIP, field.TypeString, value)
		_node.PublicIP = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(egressidentity.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if nodes := _c.mutation.RoutesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   egressidentity.RoutesTable,
			Columns: []string{egressidentity.RoutesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(egressroute.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.EgressIdentity.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.EgressIdentityUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *EgressIdentityCreate) OnConflict(opts ...sql.ConflictOption) *EgressIdentityUpsertOne {
	_c.conflict = opts
	return &EgressIdentityUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.EgressIdentity.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *EgressIdentityCreate) OnConflictColumns(columns ...string) *EgressIdentityUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &EgressIdentityUpsertOne{
		create: _c,
	}
}

type (
	// EgressIdentityUpsertOne is the builder for "upsert"-ing
	//  one EgressIdentity node.
	EgressIdentityUpsertOne struct {
		create *EgressIdentityCreate
	}

	// EgressIdentityUpsert is the "OnConflict" setter.
	EgressIdentityUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *EgressIdentityUpsert) SetUpdatedAt(v time.Time) *EgressIdentityUpsert {
	u.Set(egressidentity.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *EgressIdentityUpsert) UpdateUpdatedAt() *EgressIdentityUpsert {
	u.SetExcluded(egressidentity.FieldUpdatedAt)
	return u
}

// SetPublicIP sets the "public_ip" field.
func (u *EgressIdentityUpsert) SetPublicIP(v string) *EgressIdentityUpsert {
	u.Set(egressidentity.FieldPublicIP, v)
	return u
}

// UpdatePublicIP sets the "public_ip" field to the value that was provided on create.
func (u *EgressIdentityUpsert) UpdatePublicIP() *EgressIdentityUpsert {
	u.SetExcluded(egressidentity.FieldPublicIP)
	return u
}

// SetStatus sets the "status" field.
func (u *EgressIdentityUpsert) SetStatus(v egressidentity.Status) *EgressIdentityUpsert {
	u.Set(egressidentity.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *EgressIdentityUpsert) UpdateStatus() *EgressIdentityUpsert {
	u.SetExcluded(egressidentity.FieldStatus)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.EgressIdentity.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *EgressIdentityUpsertOne) UpdateNewValues() *EgressIdentityUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(egressidentity.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.EgressIdentity.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *EgressIdentityUpsertOne) Ignore() *EgressIdentityUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *EgressIdentityUpsertOne) DoNothing() *EgressIdentityUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the EgressIdentityCreate.OnConflict
// documentation for more info.
func (u *EgressIdentityUpsertOne) Update(set func(*EgressIdentityUpsert)) *EgressIdentityUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&EgressIdentityUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *EgressIdentityUpsertOne) SetUpdatedAt(v time.Time) *EgressIdentityUpsertOne {
	return u.Update(func(s *EgressIdentityUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *EgressIdentityUpsertOne) UpdateUpdatedAt() *EgressIdentityUpsertOne {
	return u.Update(func(s *EgressIdentityUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetPublicIP sets the "public_ip" field.
func (u *EgressIdentityUpsertOne) SetPublicIP(v string) *EgressIdentityUpsertOne {
	return u.Update(func(s *EgressIdentityUpsert) {
		s.SetPublicIP(v)
	})
}

// UpdatePublicIP sets the "public_ip" field to the value that was provided on create.
func (u *EgressIdentityUpsertOne) UpdatePublicIP() *EgressIdentityUpsertOne {
	return u.Update(func(s *EgressIdentityUpsert) {
		s.UpdatePublicIP()
	})
}

// SetStatus sets the "status" field.
func (u *EgressIdentityUpsertOne) SetStatus(v egressidentity.Status) *EgressIdentityUpsertOne {
	return u.Update(func(s *EgressIdentityUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *EgressIdentityUpsertOne) UpdateStatus() *EgressIdentityUpsertOne {
	return u.Update(func(s *EgressIdentityUpsert) {
		s.UpdateStatus()
	})
}

// Exec executes the query.
func (u *EgressIdentityUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for EgressIdentityCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *EgressIdentityUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *EgressIdentityUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *EgressIdentityUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// EgressIdentityCreateBulk is the builder for creating many EgressIdentity entities in bulk.
type EgressIdentityCreateBulk struct {
	config
	err      error
	builders []*EgressIdentityCreate
	conflict []sql.ConflictOption
}

// Save creates the EgressIdentity entities in the database.
func (_c *EgressIdentityCreateBulk) Save(ctx context.Context) ([]*EgressIdentity, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*EgressIdentity, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*EgressIdentityMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *EgressIdentityCreateBulk) SaveX(ctx context.Context) []*EgressIdentity {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EgressIdentityCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EgressIdentityCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.EgressIdentity.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.EgressIdentityUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *EgressIdentityCreateBulk) OnConflict(opts ...sql.ConflictOption) *EgressIdentityUpsertBulk {
	_c.conflict = opts
	return &EgressIdentityUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.EgressIdentity.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *EgressIdentityCreateBulk) OnConflictColumns(columns ...string) *EgressIdentityUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &EgressIdentityUpsertBulk{
		create: _c,
	}
}

// EgressIdentityUpsertBulk is the builder for "upsert"-ing
// a bulk of EgressIdentity nodes.
type EgressIdentityUpsertBulk struct {
	create *EgressIdentityCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.EgressIdentity.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *EgressIdentityUpsertBulk) UpdateNewValues() *EgressIdentityUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(egressidentity.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.EgressIdentity.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *EgressIdentityUpsertBulk) Ignore() *EgressIdentityUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *EgressIdentityUpsertBulk) DoNothing() *EgressIdentityUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the EgressIdentityCreateBulk.OnConflict
// documentation for more info.
func (u *EgressIdentityUpsertBulk) Update(set func(*EgressIdentityUpsert)) *EgressIdentityUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&EgressIdentityUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *EgressIdentityUpsertBulk) SetUpdatedAt(v time.Time) *EgressIdentityUpsertBulk {
	return u.Update(func(s *EgressIdentityUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *EgressIdentityUpsertBulk) UpdateUpdatedAt() *EgressIdentityUpsertBulk {
	return u.Update(func(s *EgressIdentityUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetPublicIP sets the "public_ip" field.
func (u *EgressIdentityUpsertBulk) SetPublicIP(v string) *EgressIdentityUpsertBulk {
	return u.Update(func(s *EgressIdentityUpsert) {
		s.SetPublicIP(v)
	})
}

// UpdatePublicIP sets the "public_ip" field to the value that was provided on create.
func (u *EgressIdentityUpsertBulk) UpdatePublicIP() *EgressIdentityUpsertBulk {
	return u.Update(func(s *EgressIdentityUpsert) {
		s.UpdatePublicIP()
	})
}

// SetStatus sets the "status" field.
func (u *EgressIdentityUpsertBulk) SetStatus(v egressidentity.Status) *EgressIdentityUpsertBulk {
	return u.Update(func(s *EgressIdentityUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *EgressIdentityUpsertBulk) UpdateStatus() *EgressIdentityUpsertBulk {
	return u.Update(func(s *EgressIdentityUpsert) {
		s.UpdateStatus()
	})
}

// Exec executes the query.
func (u *EgressIdentityUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the EgressIdentityCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for EgressIdentityCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *EgressIdentityUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
