// Code generated by ent, DO NOT EDIT.

package egressroute

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the egressroute type in the database.
	Label = "egress_route"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldKind holds the string denoting the kind field in the database.
	FieldKind = "kind"
	// FieldProxyID holds the string denoting the proxy_id field in the database.
	FieldProxyID = "proxy_id"
	// FieldRuntimeScope holds the string denoting the runtime_scope field in the database.
	FieldRuntimeScope = "runtime_scope"
	// FieldExpectedIdentityID holds the string denoting the expected_identity_id field in the database.
	FieldExpectedIdentityID = "expected_identity_id"
	// FieldState holds the string denoting the state field in the database.
	FieldState = "state"
	// FieldLastObservedIP holds the string denoting the last_observed_ip field in the database.
	FieldLastObservedIP = "last_observed_ip"
	// FieldLastProbedAt holds the string denoting the last_probed_at field in the database.
	FieldLastProbedAt = "last_probed_at"
	// FieldVerifiedAt holds the string denoting the verified_at field in the database.
	FieldVerifiedAt = "verified_at"
	// FieldRevision holds the string denoting the revision field in the database.
	FieldRevision = "revision"
	// FieldLastError holds the string denoting the last_error field in the database.
	FieldLastError = "last_error"
	// EdgeProxy holds the string denoting the proxy edge name in mutations.
	EdgeProxy = "proxy"
	// EdgeExpectedIdentity holds the string denoting the expected_identity edge name in mutations.
	EdgeExpectedIdentity = "expected_identity"
	// EdgeAccounts holds the string denoting the accounts edge name in mutations.
	EdgeAccounts = "accounts"
	// EdgeBindings holds the string denoting the bindings edge name in mutations.
	EdgeBindings = "bindings"
	// Table holds the table name of the egressroute in the database.
	Table = "egress_routes"
	// ProxyTable is the table that holds the proxy relation/edge.
	ProxyTable = "egress_routes"
	// ProxyInverseTable is the table name for the Proxy entity.
	// It exists in this package in order to avoid circular dependency with the "proxy" package.
	ProxyInverseTable = "proxies"
	// ProxyColumn is the table column denoting the proxy relation/edge.
	ProxyColumn = "proxy_id"
	// ExpectedIdentityTable is the table that holds the expected_identity relation/edge.
	ExpectedIdentityTable = "egress_routes"
	// ExpectedIdentityInverseTable is the table name for the EgressIdentity entity.
	// It exists in this package in order to avoid circular dependency with the "egressidentity" package.
	ExpectedIdentityInverseTable = "egress_identities"
	// ExpectedIdentityColumn is the table column denoting the expected_identity relation/edge.
	ExpectedIdentityColumn = "expected_identity_id"
	// AccountsTable is the table that holds the accounts relation/edge. The primary key declared below.
	AccountsTable = "account_egress_bindings"
	// AccountsInverseTable is the table name for the Account entity.
	// It exists in this package in order to avoid circular dependency with the "account" package.
	AccountsInverseTable = "accounts"
	// BindingsTable is the table that holds the bindings relation/edge.
	BindingsTable = "account_egress_bindings"
	// BindingsInverseTable is the table name for the AccountEgressBinding entity.
	// It exists in this package in order to avoid circular dependency with the "accountegressbinding" package.
	BindingsInverseTable = "account_egress_bindings"
	// BindingsColumn is the table column denoting the bindings relation/edge.
	BindingsColumn = "route_id"
)

// Columns holds all SQL columns for egressroute fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldKind,
	FieldProxyID,
	FieldRuntimeScope,
	FieldExpectedIdentityID,
	FieldState,
	FieldLastObservedIP,
	FieldLastProbedAt,
	FieldVerifiedAt,
	FieldRevision,
	FieldLastError,
}

var (
	// AccountsPrimaryKey and AccountsColumn2 are the table columns denoting the
	// primary key for the accounts relation (M2M).
	AccountsPrimaryKey = []string{"account_id", "route_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// RuntimeScopeValidator is a validator for the "runtime_scope" field. It is called by the builders before save.
	RuntimeScopeValidator func(string) error
	// DefaultRevision holds the default value on creation for the "revision" field.
	DefaultRevision int64
	// RevisionValidator is a validator for the "revision" field. It is called by the builders before save.
	RevisionValidator func(int64) error
)

// Kind defines the type for the "kind" enum field.
type Kind string

// Kind values.
const (
	KindProxy  Kind = "proxy"
	KindDirect Kind = "direct"
)

func (k Kind) String() string {
	return string(k)
}

// KindValidator is a validator for the "kind" field enum values. It is called by the builders before save.
func KindValidator(k Kind) error {
	switch k {
	case KindProxy, KindDirect:
		return nil
	default:
		return fmt.Errorf("egressroute: invalid enum value for kind field: %q", k)
	}
}

// State defines the type for the "state" enum field.
type State string

// StatePendingVerification is the default value of the State enum.
const DefaultState = StatePendingVerification

// State values.
const (
	StatePendingVerification State = "pending_verification"
	StateActive              State = "active"
	StateInactive            State = "inactive"
	StateExpired             State = "expired"
	StateIdentityMismatch    State = "identity_mismatch"
	StateRetired             State = "retired"
)

func (s State) String() string {
	return string(s)
}

// StateValidator is a validator for the "state" field enum values. It is called by the builders before save.
func StateValidator(s State) error {
	switch s {
	case StatePendingVerification, StateActive, StateInactive, StateExpired, StateIdentityMismatch, StateRetired:
		return nil
	default:
		return fmt.Errorf("egressroute: invalid enum value for state field: %q", s)
	}
}

// OrderOption defines the ordering options for the EgressRoute queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByKind orders the results by the kind field.
func ByKind(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldKind, opts...).ToFunc()
}

// ByProxyID orders the results by the proxy_id field.
func ByProxyID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProxyID, opts...).ToFunc()
}

// ByRuntimeScope orders the results by the runtime_scope field.
func ByRuntimeScope(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRuntimeScope, opts...).ToFunc()
}

// ByExpectedIdentityID orders the results by the expected_identity_id field.
func ByExpectedIdentityID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpectedIdentityID, opts...).ToFunc()
}

// ByState orders the results by the state field.
func ByState(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldState, opts...).ToFunc()
}

// ByLastObservedIP orders the results by the last_observed_ip field.
func ByLastObservedIP(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastObservedIP, opts...).ToFunc()
}

// ByLastProbedAt orders the results by the last_probed_at field.
func ByLastProbedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastProbedAt, opts...).ToFunc()
}

// ByVerifiedAt orders the results by the verified_at field.
func ByVerifiedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVerifiedAt, opts...).ToFunc()
}

// ByRevision orders the results by the revision field.
func ByRevision(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRevision, opts...).ToFunc()
}

// ByLastError orders the results by the last_error field.
func ByLastError(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastError, opts...).ToFunc()
}

// ByProxyField orders the results by proxy field.
func ByProxyField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newProxyStep(), sql.OrderByField(field, opts...))
	}
}

// ByExpectedIdentityField orders the results by expected_identity field.
func ByExpectedIdentityField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newExpectedIdentityStep(), sql.OrderByField(field, opts...))
	}
}

// ByAccountsCount orders the results by accounts count.
func ByAccountsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newAccountsStep(), opts...)
	}
}

// ByAccounts orders the results by accounts terms.
func ByAccounts(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAccountsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByBindingsCount orders the results by bindings count.
func ByBindingsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newBindingsStep(), opts...)
	}
}

// ByBindings orders the results by bindings terms.
func ByBindings(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newBindingsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newProxyStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ProxyInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, ProxyTable, ProxyColumn),
	)
}
func newExpectedIdentityStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ExpectedIdentityInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, ExpectedIdentityTable, ExpectedIdentityColumn),
	)
}
func newAccountsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AccountsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, true, AccountsTable, AccountsPrimaryKey...),
	)
}
func newBindingsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(BindingsInverseTable, BindingsColumn),
		sqlgraph.Edge(sqlgraph.O2M, true, BindingsTable, BindingsColumn),
	)
}
