// Code generated by ent, DO NOT EDIT.

package egressroute

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.EgressRoute {
	return predicate.EgressRoute(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.EgressRoute {
	return predicate.EgressRoute(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.EgressRoute {
	return predicate.EgressRoute(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.EgressRoute {
	return predicate.EgressRoute(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.EgressRoute {
	return predicate.EgressRoute(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.EgressRoute {
	return predicate.EgressRoute(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.EgressRoute {
	return predicate.EgressRoute(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.EgressRoute {
	return predicate.EgressRoute(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.EgressRoute {
	return predicate.EgressRoute(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.EgressRoute {
	return predicate.EgressRoute(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.EgressRoute {
	return predicate.EgressRoute(sql.FieldEQ(FieldUpdatedAt, v))
}

// ProxyID applies equality check predicate on the "proxy_id" field. It's identical to ProxyIDEQ.
func ProxyID(v int64) predicate.EgressRoute {
	return predicate.EgressRoute(sql.FieldEQ(FieldProxyID, v))
}

// RuntimeScope applies equality check predicate on the "runtime_scope" field. It's identical to RuntimeScopeEQ.
func RuntimeScope(v string) predicate.EgressRoute {
	return predicate.EgressRoute(sql.FieldEQ(FieldRuntimeScope, v))
}

// ExpectedIdentityID applies equality check predicate on the "expected_identity_id" field. It's identical to ExpectedIdentityIDEQ.
func ExpectedIdentityID(v int64) predicate.EgressRoute {
	return predicate.EgressRoute(sql.FieldEQ(FieldExpectedIdentityID, v))
}

// LastObservedIP applies equality check predicate on the "last_observed_ip" field. It's identical to LastObservedIPEQ.
func LastObservedIP(v string) predicate.EgressRoute {
	return predicate.EgressRoute(sql.FieldEQ(FieldLastObservedIP, v))
}

// LastProbedAt applies equality check predicate on the "last_probed_at" field. It's identical to LastProbedAtEQ.
func LastProbedAt(v time.Time) predicate.EgressRoute {
	return predicate.EgressRoute(sql.FieldEQ(FieldLastProbedAt, v))
}

// VerifiedAt applies equality check predicate on the "verified_at" field. It's identical to VerifiedAtEQ.
func VerifiedAt(v time.Time) predicate.EgressRoute {
	return predicate.EgressRoute(sql.FieldEQ(FieldVerifiedAt, v))
}

// Revision applies equality check predicate on the "revision" field. It's identical to RevisionEQ.
func Revision(v int64) predicate.EgressRoute {
	return predicate.EgressRoute(sql.FieldEQ(FieldRevision, v))
}

// LastError applies equality check predicate on the "last_error" field. It's identical to LastErrorEQ.
func LastError(v string) predicate.EgressRoute {
	return predicate.EgressRoute(sql.FieldEQ(FieldLastError, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.EgressRoute {
	return predicate.EgressRoute(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.EgressRoute {
	return predicate.EgressRoute(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.EgressRoute {
	return predicate.EgressRoute(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.EgressRoute {
	return predicate.EgressRoute(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.EgressRoute {
	return predicate.EgressRoute(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.EgressRoute {
	return predicate.EgressRoute(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.EgressRoute {
	return predicate.EgressRoute(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.EgressRoute {
	return predicate.EgressRoute(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.EgressRoute {
	return predicate.EgressRoute(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.EgressRoute {
	return predicate.EgressRoute(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.EgressRoute {
	return predicate.EgressRoute(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.EgressRoute {
	return predicate.EgressRoute(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.EgressRoute {
	return predicate.EgressRoute(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.EgressRoute {
	return predicate.EgressRoute(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.EgressRoute {
	return predicate.EgressRoute(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.EgressRoute {
	return predicate.EgressRoute(sql.FieldLTE(FieldUpdatedAt, v))
}

// KindEQ applies the EQ predicate on the "kind" field.
func KindEQ(v Kind) predicate.EgressRoute {
	return predicate.EgressRoute(sql.FieldEQ(FieldKind, v))
}

// KindNEQ applies the NEQ predicate on the "kind" field.
func KindNEQ(v Kind) predicate.EgressRoute {
	return predicate.EgressRoute(sql.FieldNEQ(FieldKind, v))
}

// KindIn applies the In predicate on the "kind" field.
func KindIn(vs ...Kind) predicate.EgressRoute {
	return predicate.EgressRoute(sql.FieldIn(FieldKind, vs...))
}

// KindNotIn applies the NotIn predicate on the "kind" field.
func KindNotIn(vs ...Kind) predicate.EgressRoute {
	return predicate.EgressRoute(sql.FieldNotIn(FieldKind, vs...))
}

// ProxyIDEQ applies the EQ predicate on the "proxy_id" field.
func ProxyIDEQ(v int64) predicate.EgressRoute {
	return predicate.EgressRoute(sql.FieldEQ(FieldProxyID, v))
}

// ProxyIDNEQ applies the NEQ predicate on the "proxy_id" field.
func ProxyIDNEQ(v int64) predicate.EgressRoute {
	return predicate.EgressRoute(sql.FieldNEQ(FieldProxyID, v))
}

// ProxyIDIn applies the In predicate on the "proxy_id" field.
func ProxyIDIn(vs ...int64) predicate.EgressRoute {
	return predicate.EgressRoute(sql.FieldIn(FieldProxyID, vs...))
}

// ProxyIDNotIn applies the NotIn predicate on the "proxy_id" field.
func ProxyIDNotIn(vs ...int64) predicate.EgressRoute {
	return predicate.EgressRoute(sql.FieldNotIn(FieldProxyID, vs...))
}

// ProxyIDIsNil applies the IsNil predicate on the "proxy_id" field.
func ProxyIDIsNil() predicate.EgressRoute {
	return predicate.EgressRoute(sql.FieldIsNull(FieldProxyID))
}

// ProxyIDNotNil applies the NotNil predicate on the "proxy_id" field.
func ProxyIDNotNil() predicate.EgressRoute {
	return predicate.EgressRoute(sql.FieldNotNull(FieldProxyID))
}

// RuntimeScopeEQ applies the EQ predicate on the "runtime_scope" field.
func RuntimeScopeEQ(v string) predicate.EgressRoute {
	return predicate.EgressRoute(sql.FieldEQ(FieldRuntimeScope, v))
}

// RuntimeScopeNEQ applies the NEQ predicate on the "runtime_scope" field.
func RuntimeScopeNEQ(v string) predicate.EgressRoute {
	return predicate.EgressRoute(sql.FieldNEQ(FieldRuntimeScope, v))
}

// RuntimeScopeIn applies the In predicate on the "runtime_scope" field.
func RuntimeScopeIn(vs ...string) predicate.EgressRoute {
	return predicate.EgressRoute(sql.FieldIn(FieldRuntimeScope, vs...))
}

// RuntimeScopeNotIn applies the NotIn predicate on the "runtime_scope" field.
func RuntimeScopeNotIn(vs ...string) predicate.EgressRoute {
	return predicate.EgressRoute(sql.FieldNotIn(FieldRuntimeScope, vs...))
}

// RuntimeScopeGT applies the GT predicate on the "runtime_scope" field.
func RuntimeScopeGT(v string) predicate.EgressRoute {
	return predicate.EgressRoute(sql.FieldGT(FieldRuntimeScope, v))
}

// RuntimeScopeGTE applies the GTE predicate on the "runtime_scope" field.
func RuntimeScopeGTE(v string) predicate.EgressRoute {
	return predicate.EgressRoute(sql.FieldGTE(FieldRuntimeScope, v))
}

// RuntimeScopeLT applies the LT predicate on the "runtime_scope" field.
func RuntimeScopeLT(v string) predicate.EgressRoute {
	return predicate.EgressRoute(sql.FieldLT(FieldRuntimeScope, v))
}

// RuntimeScopeLTE applies the LTE predicate on the "runtime_scope" field.
func RuntimeScopeLTE(v string) predicate.EgressRoute {
	return predicate.EgressRoute(sql.FieldLTE(FieldRuntimeScope, v))
}

// RuntimeScopeContains applies the Contains predicate on the "runtime_scope" field.
func RuntimeScopeContains(v string) predicate.EgressRoute {
	return predicate.EgressRoute(sql.FieldContains(FieldRuntimeScope, v))
}

// RuntimeScopeHasPrefix applies the HasPrefix predicate on the "runtime_scope" field.
func RuntimeScopeHasPrefix(v string) predicate.EgressRoute {
	return predicate.EgressRoute(sql.FieldHasPrefix(FieldRuntimeScope, v))
}

// RuntimeScopeHasSuffix applies the HasSuffix predicate on the "runtime_scope" field.
func RuntimeScopeHasSuffix(v string) predicate.EgressRoute {
	return predicate.EgressRoute(sql.FieldHasSuffix(FieldRuntimeScope, v))
}

// RuntimeScopeIsNil applies the IsNil predicate on the "runtime_scope" field.
func RuntimeScopeIsNil() predicate.EgressRoute {
	return predicate.EgressRoute(sql.FieldIsNull(FieldRuntimeScope))
}

// RuntimeScopeNotNil applies the NotNil predicate on the "runtime_scope" field.
func RuntimeScopeNotNil() predicate.EgressRoute {
	return predicate.EgressRoute(sql.FieldNotNull(FieldRuntimeScope))
}

// RuntimeScopeEqualFold applies the EqualFold predicate on the "runtime_scope" field.
func RuntimeScopeEqualFold(v string) predicate.EgressRoute {
	return predicate.EgressRoute(sql.FieldEqualFold(FieldRuntimeScope, v))
}

// RuntimeScopeContainsFold applies the ContainsFold predicate on the "runtime_scope" field.
func RuntimeScopeContainsFold(v string) predicate.EgressRoute {
	return predicate.EgressRoute(sql.FieldContainsFold(FieldRuntimeScope, v))
}

// ExpectedIdentityIDEQ applies the EQ predicate on the "expected_identity_id" field.
func ExpectedIdentityIDEQ(v int64) predicate.EgressRoute {
	return predicate.EgressRoute(sql.FieldEQ(FieldExpectedIdentityID, v))
}

// ExpectedIdentityIDNEQ applies the NEQ predicate on the "expected_identity_id" field.
func ExpectedIdentityIDNEQ(v int64) predicate.EgressRoute {
	return predicate.EgressRoute(sql.FieldNEQ(FieldExpectedIdentityID, v))
}

// ExpectedIdentityIDIn applies the In predicate on the "expected_identity_id" field.
func ExpectedIdentityIDIn(vs ...int64) predicate.EgressRoute {
	return predicate.EgressRoute(sql.FieldIn(FieldExpectedIdentityID, vs...))
}

// ExpectedIdentityIDNotIn applies the NotIn predicate on the "expected_identity_id" field.
func ExpectedIdentityIDNotIn(vs ...int64) predicate.EgressRoute {
	return predicate.EgressRoute(sql.FieldNotIn(FieldExpectedIdentityID, vs...))
}

// ExpectedIdentityIDIsNil applies the IsNil predicate on the "expected_identity_id" field.
func ExpectedIdentityIDIsNil() predicate.EgressRoute {
	return predicate.EgressRoute(sql.FieldIsNull(FieldExpectedIdentityID))
}

// ExpectedIdentityIDNotNil applies the NotNil predicate on the "expected_identity_id" field.
func ExpectedIdentityIDNotNil() predicate.EgressRoute {
	return predicate.EgressRoute(sql.FieldNotNull(FieldExpectedIdentityID))
}

// StateEQ applies the EQ predicate on the "state" field.
func StateEQ(v State) predicate.EgressRoute {
	return predicate.EgressRoute(sql.FieldEQ(FieldState, v))
}

// StateNEQ applies the NEQ predicate on the "state" field.
func StateNEQ(v State) predicate.EgressRoute {
	return predicate.EgressRoute(sql.FieldNEQ(FieldState, v))
}

// StateIn applies the In predicate on the "state" field.
func StateIn(vs ...State) predicate.EgressRoute {
	return predicate.EgressRoute(sql.FieldIn(FieldState, vs...))
}

// StateNotIn applies the NotIn predicate on the "state" field.
func StateNotIn(vs ...State) predicate.EgressRoute {
	return predicate.EgressRoute(sql.FieldNotIn(FieldState, vs...))
}

// LastObservedIPEQ applies the EQ predicate on the "last_observed_ip" field.
func LastObservedIPEQ(v string) predicate.EgressRoute {
	return predicate.EgressRoute(sql.FieldEQ(FieldLastObservedIP, v))
}

// LastObservedIPNEQ applies the NEQ predicate on the "last_observed_ip" field.
func LastObservedIPNEQ(v string) predicate.EgressRoute {
	return predicate.EgressRoute(sql.FieldNEQ(FieldLastObservedIP, v))
}

// LastObservedIPIn applies the In predicate on the "last_observed_ip" field.
func LastObservedIPIn(vs ...string) predicate.EgressRoute {
	return predicate.EgressRoute(sql.FieldIn(FieldLastObservedIP, vs...))
}

// LastObservedIPNotIn applies the NotIn predicate on the "last_observed_ip" field.
func LastObservedIPNotIn(vs ...string) predicate.EgressRoute {
	return predicate.EgressRoute(sql.FieldNotIn(FieldLastObservedIP, vs...))
}

// LastObservedIPGT applies the GT predicate on the "last_observed_ip" field.
func LastObservedIPGT(v string) predicate.EgressRoute {
	return predicate.EgressRoute(sql.FieldGT(FieldLastObservedIP, v))
}

// LastObservedIPGTE applies the GTE predicate on the "last_observed_ip" field.
func LastObservedIPGTE(v string) predicate.EgressRoute {
	return predicate.EgressRoute(sql.FieldGTE(FieldLastObservedIP, v))
}

// LastObservedIPLT applies the LT predicate on the "last_observed_ip" field.
func LastObservedIPLT(v string) predicate.EgressRoute {
	return predicate.EgressRoute(sql.FieldLT(FieldLastObservedIP, v))
}

// LastObservedIPLTE applies the LTE predicate on the "last_observed_ip" field.
func LastObservedIPLTE(v string) predicate.EgressRoute {
	return predicate.EgressRoute(sql.FieldLTE(FieldLastObservedIP, v))
}

// LastObservedIPContains applies the Contains predicate on the "last_observed_ip" field.
func LastObservedIPContains(v string) predicate.EgressRoute {
	return predicate.EgressRoute(sql.FieldContains(FieldLastObservedIP, v))
}

// LastObservedIPHasPrefix applies the HasPrefix predicate on the "last_observed_ip" field.
func LastObservedIPHasPrefix(v string) predicate.EgressRoute {
	return predicate.EgressRoute(sql.FieldHasPrefix(FieldLastObservedIP, v))
}

// LastObservedIPHasSuffix applies the HasSuffix predicate on the "last_observed_ip" field.
func LastObservedIPHasSuffix(v string) predicate.EgressRoute {
	return predicate.EgressRoute(sql.FieldHasSuffix(FieldLastObservedIP, v))
}

// LastObservedIPIsNil applies the IsNil predicate on the "last_observed_ip" field.
func LastObservedIPIsNil() predicate.EgressRoute {
	return predicate.EgressRoute(sql.FieldIsNull(FieldLastObservedIP))
}

// LastObservedIPNotNil applies the NotNil predicate on the "last_observed_ip" field.
func LastObservedIPNotNil() predicate.EgressRoute {
	return predicate.EgressRoute(sql.FieldNotNull(FieldLastObservedIP))
}

// LastObservedIPEqualFold applies the EqualFold predicate on the "last_observed_ip" field.
func LastObservedIPEqualFold(v string) predicate.EgressRoute {
	return predicate.EgressRoute(sql.FieldEqualFold(FieldLastObservedIP, v))
}

// LastObservedIPContainsFold applies the ContainsFold predicate on the "last_observed_ip" field.
func LastObservedIPContainsFold(v string) predicate.EgressRoute {
	return predicate.EgressRoute(sql.FieldContainsFold(FieldLastObservedIP, v))
}

// LastProbedAtEQ applies the EQ predicate on the "last_probed_at" field.
func LastProbedAtEQ(v time.Time) predicate.EgressRoute {
	return predicate.EgressRoute(sql.FieldEQ(FieldLastProbedAt, v))
}

// LastProbedAtNEQ applies the NEQ predicate on the "last_probed_at" field.
func LastProbedAtNEQ(v time.Time) predicate.EgressRoute {
	return predicate.EgressRoute(sql.FieldNEQ(FieldLastProbedAt, v))
}

// LastProbedAtIn applies the In predicate on the "last_probed_at" field.
func LastProbedAtIn(vs ...time.Time) predicate.EgressRoute {
	return predicate.EgressRoute(sql.FieldIn(FieldLastProbedAt, vs...))
}

// LastProbedAtNotIn applies the NotIn predicate on the "last_probed_at" field.
func LastProbedAtNotIn(vs ...time.Time) predicate.EgressRoute {
	return predicate.EgressRoute(sql.FieldNotIn(FieldLastProbedAt, vs...))
}

// LastProbedAtGT applies the GT predicate on the "last_probed_at" field.
func LastProbedAtGT(v time.Time) predicate.EgressRoute {
	return predicate.EgressRoute(sql.FieldGT(FieldLastProbedAt, v))
}

// LastProbedAtGTE applies the GTE predicate on the "last_probed_at" field.
func LastProbedAtGTE(v time.Time) predicate.EgressRoute {
	return predicate.EgressRoute(sql.FieldGTE(FieldLastProbedAt, v))
}

// LastProbedAtLT applies the LT predicate on the "last_probed_at" field.
func LastProbedAtLT(v time.Time) predicate.EgressRoute {
	return predicate.EgressRoute(sql.FieldLT(FieldLastProbedAt, v))
}

// LastProbedAtLTE applies the LTE predicate on the "last_probed_at" field.
func LastProbedAtLTE(v time.Time) predicate.EgressRoute {
	return predicate.EgressRoute(sql.FieldLTE(FieldLastProbedAt, v))
}

// LastProbedAtIsNil applies the IsNil predicate on the "last_probed_at" field.
func LastProbedAtIsNil() predicate.EgressRoute {
	return predicate.EgressRoute(sql.FieldIsNull(FieldLastProbedAt))
}

// LastProbedAtNotNil applies the NotNil predicate on the "last_probed_at" field.
func LastProbedAtNotNil() predicate.EgressRoute {
	return predicate.EgressRoute(sql.FieldNotNull(FieldLastProbedAt))
}

// VerifiedAtEQ applies the EQ predicate on the "verified_at" field.
func VerifiedAtEQ(v time.Time) predicate.EgressRoute {
	return predicate.EgressRoute(sql.FieldEQ(FieldVerifiedAt, v))
}

// VerifiedAtNEQ applies the NEQ predicate on the "verified_at" field.
func VerifiedAtNEQ(v time.Time) predicate.EgressRoute {
	return predicate.EgressRoute(sql.FieldNEQ(FieldVerifiedAt, v))
}

// VerifiedAtIn applies the In predicate on the "verified_at" field.
func VerifiedAtIn(vs ...time.Time) predicate.EgressRoute {
	return predicate.EgressRoute(sql.FieldIn(FieldVerifiedAt, vs...))
}

// VerifiedAtNotIn applies the NotIn predicate on the "verified_at" field.
func VerifiedAtNotIn(vs ...time.Time) predicate.EgressRoute {
	return predicate.EgressRoute(sql.FieldNotIn(FieldVerifiedAt, vs...))
}

// VerifiedAtGT applies the GT predicate on the "verified_at" field.
func VerifiedAtGT(v time.Time) predicate.EgressRoute {
	return predicate.EgressRoute(sql.FieldGT(FieldVerifiedAt, v))
}

// VerifiedAtGTE applies the GTE predicate on the "verified_at" field.
func VerifiedAtGTE(v time.Time) predicate.EgressRoute {
	return predicate.EgressRoute(sql.FieldGTE(FieldVerifiedAt, v))
}

// VerifiedAtLT applies the LT predicate on the "verified_at" field.
func VerifiedAtLT(v time.Time) predicate.EgressRoute {
	return predicate.EgressRoute(sql.FieldLT(FieldVerifiedAt, v))
}

// VerifiedAtLTE applies the LTE predicate on the "verified_at" field.
func VerifiedAtLTE(v time.Time) predicate.EgressRoute {
	return predicate.EgressRoute(sql.FieldLTE(FieldVerifiedAt, v))
}

// VerifiedAtIsNil applies the IsNil predicate on the "verified_at" field.
func VerifiedAtIsNil() predicate.EgressRoute {
	return predicate.EgressRoute(sql.FieldIsNull(FieldVerifiedAt))
}

// VerifiedAtNotNil applies the NotNil predicate on the "verified_at" field.
func VerifiedAtNotNil() predicate.EgressRoute {
	return predicate.EgressRoute(sql.FieldNotNull(FieldVerifiedAt))
}

// RevisionEQ applies the EQ predicate on the "revision" field.
func RevisionEQ(v int64) predicate.EgressRoute {
	return predicate.EgressRoute(sql.FieldEQ(FieldRevision, v))
}

// RevisionNEQ applies the NEQ predicate on the "revision" field.
func RevisionNEQ(v int64) predicate.EgressRoute {
	return predicate.EgressRoute(sql.FieldNEQ(FieldRevision, v))
}

// RevisionIn applies the In predicate on the "revision" field.
func RevisionIn(vs ...int64) predicate.EgressRoute {
	return predicate.EgressRoute(sql.FieldIn(FieldRevision, vs...))
}

// RevisionNotIn applies the NotIn predicate on the "revision" field.
func RevisionNotIn(vs ...int64) predicate.EgressRoute {
	return predicate.EgressRoute(sql.FieldNotIn(FieldRevision, vs...))
}

// RevisionGT applies the GT predicate on the "revision" field.
func RevisionGT(v int64) predicate.EgressRoute {
	return predicate.EgressRoute(sql.FieldGT(FieldRevision, v))
}

// RevisionGTE applies the GTE predicate on the "revision" field.
func RevisionGTE(v int64) predicate.EgressRoute {
	return predicate.EgressRoute(sql.FieldGTE(FieldRevision, v))
}

// RevisionLT applies the LT predicate on the "revision" field.
func RevisionLT(v int64) predicate.EgressRoute {
	return predicate.EgressRoute(sql.FieldLT(FieldRevision, v))
}

// RevisionLTE applies the LTE predicate on the "revision" field.
func RevisionLTE(v int64) predicate.EgressRoute {
	return predicate.EgressRoute(sql.FieldLTE(FieldRevision, v))
}

// LastErrorEQ applies the EQ predicate on the "last_error" field.
func LastErrorEQ(v string) predicate.EgressRoute {
	return predicate.EgressRoute(sql.FieldEQ(FieldLastError, v))
}

// LastErrorNEQ applies the NEQ predicate on the "last_error" field.
func LastErrorNEQ(v string) predicate.EgressRoute {
	return predicate.EgressRoute(sql.FieldNEQ(FieldLastError, v))
}

// LastErrorIn applies the In predicate on the "last_error" field.
func LastErrorIn(vs ...string) predicate.EgressRoute {
	return predicate.EgressRoute(sql.FieldIn(FieldLastError, vs...))
}

// LastErrorNotIn applies the NotIn predicate on the "last_error" field.
func LastErrorNotIn(vs ...string) predicate.EgressRoute {
	return predicate.EgressRoute(sql.FieldNotIn(FieldLastError, vs...))
}

// LastErrorGT applies the GT predicate on the "last_error" field.
func LastErrorGT(v string) predicate.EgressRoute {
	return predicate.EgressRoute(sql.FieldGT(FieldLastError, v))
}

// LastErrorGTE applies the GTE predicate on the "last_error" field.
func LastErrorGTE(v string) predicate.EgressRoute {
	return predicate.EgressRoute(sql.FieldGTE(FieldLastError, v))
}

// LastErrorLT applies the LT predicate on the "last_error" field.
func LastErrorLT(v string) predicate.EgressRoute {
	return predicate.EgressRoute(sql.FieldLT(FieldLastError, v))
}

// LastErrorLTE applies the LTE predicate on the "last_error" field.
func LastErrorLTE(v string) predicate.EgressRoute {
	return predicate.EgressRoute(sql.FieldLTE(FieldLastError, v))
}

// LastErrorContains applies the Contains predicate on the "last_error" field.
func LastErrorContains(v string) predicate.EgressRoute {
	return predicate.EgressRoute(sql.FieldContains(FieldLastError, v))
}

// LastErrorHasPrefix applies the HasPrefix predicate on the "last_error" field.
func LastErrorHasPrefix(v string) predicate.EgressRoute {
	return predicate.EgressRoute(sql.FieldHasPrefix(FieldLastError, v))
}

// LastErrorHasSuffix applies the HasSuffix predicate on the "last_error" field.
func LastErrorHasSuffix(v string) predicate.EgressRoute {
	return predicate.EgressRoute(sql.FieldHasSuffix(FieldLastError, v))
}

// LastErrorIsNil applies the IsNil predicate on the "last_error" field.
func LastErrorIsNil() predicate.EgressRoute {
	return predicate.EgressRoute(sql.FieldIsNull(FieldLastError))
}

// LastErrorNotNil applies the NotNil predicate on the "last_error" field.
func LastErrorNotNil() predicate.EgressRoute {
	return predicate.EgressRoute(sql.FieldNotNull(FieldLastError))
}

// LastErrorEqualFold applies the EqualFold predicate on the "last_error" field.
func LastErrorEqualFold(v string) predicate.EgressRoute {
	return predicate.EgressRoute(sql.FieldEqualFold(FieldLastError, v))
}

// LastErrorContainsFold applies the ContainsFold predicate on the "last_error" field.
func LastErrorContainsFold(v string) predicate.EgressRoute {
	return predicate.EgressRoute(sql.FieldContainsFold(FieldLastError, v))
}

// HasProxy applies the HasEdge predicate on the "proxy" edge.
func HasProxy() predicate.EgressRoute {
	return predicate.EgressRoute(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, ProxyTable, ProxyColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasProxyWith applies the HasEdge predicate on the "proxy" edge with a given conditions (other predicates).
func HasProxyWith(preds ...predicate.Proxy) predicate.EgressRoute {
	return predicate.EgressRoute(func(s *sql.Selector) {
		step := newProxyStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasExpectedIdentity applies the HasEdge predicate on the "expected_identity" edge.
func HasExpectedIdentity() predicate.EgressRoute {
	return predicate.EgressRoute(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, ExpectedIdentityTable, ExpectedIdentityColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasExpectedIdentityWith applies the HasEdge predicate on the "expected_identity" edge with a given conditions (other predicates).
func HasExpectedIdentityWith(preds ...predicate.EgressIdentity) predicate.EgressRoute {
	return predicate.EgressRoute(func(s *sql.Selector) {
		step := newExpectedIdentityStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAccounts applies the HasEdge predicate on the "accounts" edge.
func HasAccounts() predicate.EgressRoute {
	return predicate.EgressRoute(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, AccountsTable, AccountsPrimaryKey...),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAccountsWith applies the HasEdge predicate on the "accounts" edge with a given conditions (other predicates).
func HasAccountsWith(preds ...predicate.Account) predicate.EgressRoute {
	return predicate.EgressRoute(func(s *sql.Selector) {
		step := newAccountsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasBindings applies the HasEdge predicate on the "bindings" edge.
func HasBindings() predicate.EgressRoute {
	return predicate.EgressRoute(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, BindingsTable, BindingsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasBindingsWith applies the HasEdge predicate on the "bindings" edge with a given conditions (other predicates).
func HasBindingsWith(preds ...predicate.AccountEgressBinding) predicate.EgressRoute {
	return predicate.EgressRoute(func(s *sql.Selector) {
		step := newBindingsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.EgressRoute) predicate.EgressRoute {
	return predicate.EgressRoute(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.EgressRoute) predicate.EgressRoute {
	return predicate.EgressRoute(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.EgressRoute) predicate.EgressRoute {
	return predicate.EgressRoute(sql.NotPredicates(p))
}
