// Code generated by ent, DO NOT EDIT.

package accountegressbinding

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the accountegressbinding type in the database.
	Label = "account_egress_binding"
	// FieldAccountID holds the string denoting the account_id field in the database.
	FieldAccountID = "account_id"
	// FieldRouteID holds the string denoting the route_id field in the database.
	FieldRouteID = "route_id"
	// FieldPosition holds the string denoting the position field in the database.
	FieldPosition = "position"
	// FieldIsPrimary holds the string denoting the is_primary field in the database.
	FieldIsPrimary = "is_primary"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeAccount holds the string denoting the account edge name in mutations.
	EdgeAccount = "account"
	// EdgeRoute holds the string denoting the route edge name in mutations.
	EdgeRoute = "route"
	// AccountFieldID holds the string denoting the ID field of the Account.
	AccountFieldID = "id"
	// EgressRouteFieldID holds the string denoting the ID field of the EgressRoute.
	EgressRouteFieldID = "id"
	// Table holds the table name of the accountegressbinding in the database.
	Table = "account_egress_bindings"
	// AccountTable is the table that holds the account relation/edge.
	AccountTable = "account_egress_bindings"
	// AccountInverseTable is the table name for the Account entity.
	// It exists in this package in order to avoid circular dependency with the "account" package.
	AccountInverseTable = "accounts"
	// AccountColumn is the table column denoting the account relation/edge.
	AccountColumn = "account_id"
	// RouteTable is the table that holds the route relation/edge.
	RouteTable = "account_egress_bindings"
	// RouteInverseTable is the table name for the EgressRoute entity.
	// It exists in this package in order to avoid circular dependency with the "egressroute" package.
	RouteInverseTable = "egress_routes"
	// RouteColumn is the table column denoting the route relation/edge.
	RouteColumn = "route_id"
)

// Columns holds all SQL columns for accountegressbinding fields.
var Columns = []string{
	FieldAccountID,
	FieldRouteID,
	FieldPosition,
	FieldIsPrimary,
	FieldStatus,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultPosition holds the default value on creation for the "position" field.
	DefaultPosition int
	// PositionValidator is a validator for the "position" field. It is called by the builders before save.
	PositionValidator func(int) error
	// DefaultIsPrimary holds the default value on creation for the "is_primary" field.
	DefaultIsPrimary bool
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// Status defines the type for the "status" enum field.
type Status string

// StatusActive is the default value of the Status enum.
const DefaultStatus = StatusActive

// Status values.
const (
	StatusActive   Status = "active"
	StatusDraining Status = "draining"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusActive, StatusDraining:
		return nil
	default:
		return fmt.Errorf("accountegressbinding: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the AccountEgressBinding queries.
type OrderOption func(*sql.Selector)

// ByAccountID orders the results by the account_id field.
func ByAccountID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccountID, opts...).ToFunc()
}

// ByRouteID orders the results by the route_id field.
func ByRouteID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRouteID, opts...).ToFunc()
}

// ByPosition orders the results by the position field.
func ByPosition(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPosition, opts...).ToFunc()
}

// ByIsPrimary orders the results by the is_primary field.
func ByIsPrimary(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsPrimary, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByAccountField orders the results by account field.
func ByAccountField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAccountStep(), sql.OrderByField(field, opts...))
	}
}

// ByRouteField orders the results by route field.
func ByRouteField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newRouteStep(), sql.OrderByField(field, opts...))
	}
}
func newAccountStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, AccountColumn),
		sqlgraph.To(AccountInverseTable, AccountFieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, AccountTable, AccountColumn),
	)
}
func newRouteStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, RouteColumn),
		sqlgraph.To(RouteInverseTable, EgressRouteFieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, RouteTable, RouteColumn),
	)
}
