// Code generated by ent, DO NOT EDIT.

package accountegressbinding

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// AccountID applies equality check predicate on the "account_id" field. It's identical to AccountIDEQ.
func AccountID(v int64) predicate.AccountEgressBinding {
	return predicate.AccountEgressBinding(sql.FieldEQ(FieldAccountID, v))
}

// RouteID applies equality check predicate on the "route_id" field. It's identical to RouteIDEQ.
func RouteID(v int64) predicate.AccountEgressBinding {
	return predicate.AccountEgressBinding(sql.FieldEQ(FieldRouteID, v))
}

// Position applies equality check predicate on the "position" field. It's identical to PositionEQ.
func Position(v int) predicate.AccountEgressBinding {
	return predicate.AccountEgressBinding(sql.FieldEQ(FieldPosition, v))
}

// IsPrimary applies equality check predicate on the "is_primary" field. It's identical to IsPrimaryEQ.
func IsPrimary(v bool) predicate.AccountEgressBinding {
	return predicate.AccountEgressBinding(sql.FieldEQ(FieldIsPrimary, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.AccountEgressBinding {
	return predicate.AccountEgressBinding(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.AccountEgressBinding {
	return predicate.AccountEgressBinding(sql.FieldEQ(FieldUpdatedAt, v))
}

// AccountIDEQ applies the EQ predicate on the "account_id" field.
func AccountIDEQ(v int64) predicate.AccountEgressBinding {
	return predicate.AccountEgressBinding(sql.FieldEQ(FieldAccountID, v))
}

// AccountIDNEQ applies the NEQ predicate on the "account_id" field.
func AccountIDNEQ(v int64) predicate.AccountEgressBinding {
	return predicate.AccountEgressBinding(sql.FieldNEQ(FieldAccountID, v))
}

// AccountIDIn applies the In predicate on the "account_id" field.
func AccountIDIn(vs ...int64) predicate.AccountEgressBinding {
	return predicate.AccountEgressBinding(sql.FieldIn(FieldAccountID, vs...))
}

// AccountIDNotIn applies the NotIn predicate on the "account_id" field.
func AccountIDNotIn(vs ...int64) predicate.AccountEgressBinding {
	return predicate.AccountEgressBinding(sql.FieldNotIn(FieldAccountID, vs...))
}

// RouteIDEQ applies the EQ predicate on the "route_id" field.
func RouteIDEQ(v int64) predicate.AccountEgressBinding {
	return predicate.AccountEgressBinding(sql.FieldEQ(FieldRouteID, v))
}

// RouteIDNEQ applies the NEQ predicate on the "route_id" field.
func RouteIDNEQ(v int64) predicate.AccountEgressBinding {
	return predicate.AccountEgressBinding(sql.FieldNEQ(FieldRouteID, v))
}

// RouteIDIn applies the In predicate on the "route_id" field.
func RouteIDIn(vs ...int64) predicate.AccountEgressBinding {
	return predicate.AccountEgressBinding(sql.FieldIn(FieldRouteID, vs...))
}

// RouteIDNotIn applies the NotIn predicate on the "route_id" field.
func RouteIDNotIn(vs ...int64) predicate.AccountEgressBinding {
	return predicate.AccountEgressBinding(sql.FieldNotIn(FieldRouteID, vs...))
}

// PositionEQ applies the EQ predicate on the "position" field.
func PositionEQ(v int) predicate.AccountEgressBinding {
	return predicate.AccountEgressBinding(sql.FieldEQ(FieldPosition, v))
}

// PositionNEQ applies the NEQ predicate on the "position" field.
func PositionNEQ(v int) predicate.AccountEgressBinding {
	return predicate.AccountEgressBinding(sql.FieldNEQ(FieldPosition, v))
}

// PositionIn applies the In predicate on the "position" field.
func PositionIn(vs ...int) predicate.AccountEgressBinding {
	return predicate.AccountEgressBinding(sql.FieldIn(FieldPosition, vs...))
}

// PositionNotIn applies the NotIn predicate on the "position" field.
func PositionNotIn(vs ...int) predicate.AccountEgressBinding {
	return predicate.AccountEgressBinding(sql.FieldNotIn(FieldPosition, vs...))
}

// PositionGT applies the GT predicate on the "position" field.
func PositionGT(v int) predicate.AccountEgressBinding {
	return predicate.AccountEgressBinding(sql.FieldGT(FieldPosition, v))
}

// PositionGTE applies the GTE predicate on the "position" field.
func PositionGTE(v int) predicate.AccountEgressBinding {
	return predicate.AccountEgressBinding(sql.FieldGTE(FieldPosition, v))
}

// PositionLT applies the LT predicate on the "position" field.
func PositionLT(v int) predicate.AccountEgressBinding {
	return predicate.AccountEgressBinding(sql.FieldLT(FieldPosition, v))
}

// PositionLTE applies the LTE predicate on the "position" field.
func PositionLTE(v int) predicate.AccountEgressBinding {
	return predicate.AccountEgressBinding(sql.FieldLTE(FieldPosition, v))
}

// IsPrimaryEQ applies the EQ predicate on the "is_primary" field.
func IsPrimaryEQ(v bool) predicate.AccountEgressBinding {
	return predicate.AccountEgressBinding(sql.FieldEQ(FieldIsPrimary, v))
}

// IsPrimaryNEQ applies the NEQ predicate on the "is_primary" field.
func IsPrimaryNEQ(v bool) predicate.AccountEgressBinding {
	return predicate.AccountEgressBinding(sql.FieldNEQ(FieldIsPrimary, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.AccountEgressBinding {
	return predicate.AccountEgressBinding(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.AccountEgressBinding {
	return predicate.AccountEgressBinding(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.AccountEgressBinding {
	return predicate.AccountEgressBinding(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.AccountEgressBinding {
	return predicate.AccountEgressBinding(sql.FieldNotIn(FieldStatus, vs...))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.AccountEgressBinding {
	return predicate.AccountEgressBinding(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.AccountEgressBinding {
	return predicate.AccountEgressBinding(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.AccountEgressBinding {
	return predicate.AccountEgressBinding(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.AccountEgressBinding {
	return predicate.AccountEgressBinding(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.AccountEgressBinding {
	return predicate.AccountEgressBinding(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.AccountEgressBinding {
	return predicate.AccountEgressBinding(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.AccountEgressBinding {
	return predicate.AccountEgressBinding(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.AccountEgressBinding {
	return predicate.AccountEgressBinding(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.AccountEgressBinding {
	return predicate.AccountEgressBinding(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.AccountEgressBinding {
	return predicate.AccountEgressBinding(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.AccountEgressBinding {
	return predicate.AccountEgressBinding(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.AccountEgressBinding {
	return predicate.AccountEgressBinding(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.AccountEgressBinding {
	return predicate.AccountEgressBinding(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.AccountEgressBinding {
	return predicate.AccountEgressBinding(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.AccountEgressBinding {
	return predicate.AccountEgressBinding(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.AccountEgressBinding {
	return predicate.AccountEgressBinding(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasAccount applies the HasEdge predicate on the "account" edge.
func HasAccount() predicate.AccountEgressBinding {
	return predicate.AccountEgressBinding(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, AccountColumn),
			sqlgraph.Edge(sqlgraph.M2O, false, AccountTable, AccountColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAccountWith applies the HasEdge predicate on the "account" edge with a given conditions (other predicates).
func HasAccountWith(preds ...predicate.Account) predicate.AccountEgressBinding {
	return predicate.AccountEgressBinding(func(s *sql.Selector) {
		step := newAccountStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasRoute applies the HasEdge predicate on the "route" edge.
func HasRoute() predicate.AccountEgressBinding {
	return predicate.AccountEgressBinding(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, RouteColumn),
			sqlgraph.Edge(sqlgraph.M2O, false, RouteTable, RouteColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRouteWith applies the HasEdge predicate on the "route" edge with a given conditions (other predicates).
func HasRouteWith(preds ...predicate.EgressRoute) predicate.AccountEgressBinding {
	return predicate.AccountEgressBinding(func(s *sql.Selector) {
		step := newRouteStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AccountEgressBinding) predicate.AccountEgressBinding {
	return predicate.AccountEgressBinding(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AccountEgressBinding) predicate.AccountEgressBinding {
	return predicate.AccountEgressBinding(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AccountEgressBinding) predicate.AccountEgressBinding {
	return predicate.AccountEgressBinding(sql.NotPredicates(p))
}
