// Code generated by ent, DO NOT EDIT.

package egressidentity

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.EgressIdentity {
	return predicate.EgressIdentity(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.EgressIdentity {
	return predicate.EgressIdentity(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.EgressIdentity {
	return predicate.EgressIdentity(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.EgressIdentity {
	return predicate.EgressIdentity(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.EgressIdentity {
	return predicate.EgressIdentity(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.EgressIdentity {
	return predicate.EgressIdentity(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.EgressIdentity {
	return predicate.EgressIdentity(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.EgressIdentity {
	return predicate.EgressIdentity(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.EgressIdentity {
	return predicate.EgressIdentity(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.EgressIdentity {
	return predicate.EgressIdentity(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.EgressIdentity {
	return predicate.EgressIdentity(sql.FieldEQ(FieldUpdatedAt, v))
}

// PublicIP applies equality check predicate on the "public_ip" field. It's identical to PublicIPEQ.
func PublicIP(v string) predicate.EgressIdentity {
	return predicate.EgressIdentity(sql.FieldEQ(FieldPublicIP, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.EgressIdentity {
	return predicate.EgressIdentity(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.EgressIdentity {
	return predicate.EgressIdentity(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.EgressIdentity {
	return predicate.EgressIdentity(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.EgressIdentity {
	return predicate.EgressIdentity(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.EgressIdentity {
	return predicate.EgressIdentity(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.EgressIdentity {
	return predicate.EgressIdentity(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.EgressIdentity {
	return predicate.EgressIdentity(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.EgressIdentity {
	return predicate.EgressIdentity(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.EgressIdentity {
	return predicate.EgressIdentity(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.EgressIdentity {
	return predicate.EgressIdentity(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.EgressIdentity {
	return predicate.EgressIdentity(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.EgressIdentity {
	return predicate.EgressIdentity(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.EgressIdentity {
	return predicate.EgressIdentity(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.EgressIdentity {
	return predicate.EgressIdentity(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.EgressIdentity {
	return predicate.EgressIdentity(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.EgressIdentity {
	return predicate.EgressIdentity(sql.FieldLTE(FieldUpdatedAt, v))
}

// PublicIPEQ applies the EQ predicate on the "public_ip" field.
func PublicIPEQ(v string) predicate.EgressIdentity {
	return predicate.EgressIdentity(sql.FieldEQ(FieldPublicIP, v))
}

// PublicIPNEQ applies the NEQ predicate on the "public_ip" field.
func PublicIPNEQ(v string) predicate.EgressIdentity {
	return predicate.EgressIdentity(sql.FieldNEQ(FieldPublicIP, v))
}

// PublicIPIn applies the In predicate on the "public_ip" field.
func PublicIPIn(vs ...string) predicate.EgressIdentity {
	return predicate.EgressIdentity(sql.FieldIn(FieldPublicIP, vs...))
}

// PublicIPNotIn applies the NotIn predicate on the "public_ip" field.
func PublicIPNotIn(vs ...string) predicate.EgressIdentity {
	return predicate.EgressIdentity(sql.FieldNotIn(FieldPublicIP, vs...))
}

// PublicIPGT applies the GT predicate on the "public_ip" field.
func PublicIPGT(v string) predicate.EgressIdentity {
	return predicate.EgressIdentity(sql.FieldGT(FieldPublicIP, v))
}

// PublicIPGTE applies the GTE predicate on the "public_ip" field.
func PublicIPGTE(v string) predicate.EgressIdentity {
	return predicate.EgressIdentity(sql.FieldGTE(FieldPublicIP, v))
}

// PublicIPLT applies the LT predicate on the "public_ip" field.
func PublicIPLT(v string) predicate.EgressIdentity {
	return predicate.EgressIdentity(sql.FieldLT(FieldPublicIP, v))
}

// PublicIPLTE applies the LTE predicate on the "public_ip" field.
func PublicIPLTE(v string) predicate.EgressIdentity {
	return predicate.EgressIdentity(sql.FieldLTE(FieldPublicIP, v))
}

// PublicIPContains applies the Contains predicate on the "public_ip" field.
func PublicIPContains(v string) predicate.EgressIdentity {
	return predicate.EgressIdentity(sql.FieldContains(FieldPublicIP, v))
}

// PublicIPHasPrefix applies the HasPrefix predicate on the "public_ip" field.
func PublicIPHasPrefix(v string) predicate.EgressIdentity {
	return predicate.EgressIdentity(sql.FieldHasPrefix(FieldPublicIP, v))
}

// PublicIPHasSuffix applies the HasSuffix predicate on the "public_ip" field.
func PublicIPHasSuffix(v string) predicate.EgressIdentity {
	return predicate.EgressIdentity(sql.FieldHasSuffix(FieldPublicIP, v))
}

// PublicIPEqualFold applies the EqualFold predicate on the "public_ip" field.
func PublicIPEqualFold(v string) predicate.EgressIdentity {
	return predicate.EgressIdentity(sql.FieldEqualFold(FieldPublicIP, v))
}

// PublicIPContainsFold applies the ContainsFold predicate on the "public_ip" field.
func PublicIPContainsFold(v string) predicate.EgressIdentity {
	return predicate.EgressIdentity(sql.FieldContainsFold(FieldPublicIP, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.EgressIdentity {
	return predicate.EgressIdentity(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.EgressIdentity {
	return predicate.EgressIdentity(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.EgressIdentity {
	return predicate.EgressIdentity(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.EgressIdentity {
	return predicate.EgressIdentity(sql.FieldNotIn(FieldStatus, vs...))
}

// HasRoutes applies the HasEdge predicate on the "routes" edge.
func HasRoutes() predicate.EgressIdentity {
	return predicate.EgressIdentity(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, RoutesTable, RoutesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRoutesWith applies the HasEdge predicate on the "routes" edge with a given conditions (other predicates).
func HasRoutesWith(preds ...predicate.EgressRoute) predicate.EgressIdentity {
	return predicate.EgressIdentity(func(s *sql.Selector) {
		step := newRoutesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.EgressIdentity) predicate.EgressIdentity {
	return predicate.EgressIdentity(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.EgressIdentity) predicate.EgressIdentity {
	return predicate.EgressIdentity(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.EgressIdentity) predicate.EgressIdentity {
	return predicate.EgressIdentity(sql.NotPredicates(p))
}
